// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/balance.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BalanceSnapshotBody — tracker-signed credit balance for an identity.
// Spec: docs/superpowers/specs/ledger/2026-04-22-ledger-design.md §3.4.
// Two-message split for canonical signing: tracker signs DeterministicMarshal(body).
type BalanceSnapshotBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    []byte                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"` // 32 bytes — Ed25519 pubkey hash
	Credits       int64                  `protobuf:"varint,2,opt,name=credits,proto3" json:"credits,omitempty"`
	ChainTipHash  []byte                 `protobuf:"bytes,3,opt,name=chain_tip_hash,json=chainTipHash,proto3" json:"chain_tip_hash,omitempty"` // 32 bytes
	ChainTipSeq   uint64                 `protobuf:"varint,4,opt,name=chain_tip_seq,json=chainTipSeq,proto3" json:"chain_tip_seq,omitempty"`
	IssuedAt      uint64                 `protobuf:"varint,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`    // unix seconds
	ExpiresAt     uint64                 `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // issued_at + 600 (10-minute freshness window)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceSnapshotBody) Reset() {
	*x = BalanceSnapshotBody{}
	mi := &file_proto_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceSnapshotBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceSnapshotBody) ProtoMessage() {}

func (x *BalanceSnapshotBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceSnapshotBody.ProtoReflect.Descriptor instead.
func (*BalanceSnapshotBody) Descriptor() ([]byte, []int) {
	return file_proto_balance_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceSnapshotBody) GetIdentityId() []byte {
	if x != nil {
		return x.IdentityId
	}
	return nil
}

func (x *BalanceSnapshotBody) GetCredits() int64 {
	if x != nil {
		return x.Credits
	}
	return 0
}

func (x *BalanceSnapshotBody) GetChainTipHash() []byte {
	if x != nil {
		return x.ChainTipHash
	}
	return nil
}

func (x *BalanceSnapshotBody) GetChainTipSeq() uint64 {
	if x != nil {
		return x.ChainTipSeq
	}
	return 0
}

func (x *BalanceSnapshotBody) GetIssuedAt() uint64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *BalanceSnapshotBody) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// SignedBalanceSnapshot — wire form. Verifier recovers signed bytes via
// shared/signing.DeterministicMarshal(body).
type SignedBalanceSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *BalanceSnapshotBody   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	TrackerSig    []byte                 `protobuf:"bytes,2,opt,name=tracker_sig,json=trackerSig,proto3" json:"tracker_sig,omitempty"` // 64 bytes — Ed25519 signature
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedBalanceSnapshot) Reset() {
	*x = SignedBalanceSnapshot{}
	mi := &file_proto_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedBalanceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedBalanceSnapshot) ProtoMessage() {}

func (x *SignedBalanceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedBalanceSnapshot.ProtoReflect.Descriptor instead.
func (*SignedBalanceSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_balance_proto_rawDescGZIP(), []int{1}
}

func (x *SignedBalanceSnapshot) GetBody() *BalanceSnapshotBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SignedBalanceSnapshot) GetTrackerSig() []byte {
	if x != nil {
		return x.TrackerSig
	}
	return nil
}

var File_proto_balance_proto protoreflect.FileDescriptor

const file_proto_balance_proto_rawDesc = "" +
	"\n" +
	"\x13proto/balance.proto\x12\x11tokenbay.proto.v1\"\xd6\x01\n" +
	"\x13BalanceSnapshotBody\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\fR\n" +
	"identityId\x12\x18\n" +
	"\acredits\x18\x02 \x01(\x03R\acredits\x12$\n" +
	"\x0echain_tip_hash\x18\x03 \x01(\fR\fchainTipHash\x12\"\n" +
	"\rchain_tip_seq\x18\x04 \x01(\x04R\vchainTipSeq\x12\x1b\n" +
	"\tissued_at\x18\x05 \x01(\x04R\bissuedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x04R\texpiresAt\"t\n" +
	"\x15SignedBalanceSnapshot\x12:\n" +
	"\x04body\x18\x01 \x01(\v2&.tokenbay.proto.v1.BalanceSnapshotBodyR\x04body\x12\x1f\n" +
	"\vtracker_sig\x18\x02 \x01(\fR\n" +
	"trackerSigB-Z+github.com/token-bay/token-bay/shared/protob\x06proto3"

var (
	file_proto_balance_proto_rawDescOnce sync.Once
	file_proto_balance_proto_rawDescData []byte
)

func file_proto_balance_proto_rawDescGZIP() []byte {
	file_proto_balance_proto_rawDescOnce.Do(func() {
		file_proto_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_balance_proto_rawDesc), len(file_proto_balance_proto_rawDesc)))
	})
	return file_proto_balance_proto_rawDescData
}

var file_proto_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_balance_proto_goTypes = []any{
	(*BalanceSnapshotBody)(nil),   // 0: tokenbay.proto.v1.BalanceSnapshotBody
	(*SignedBalanceSnapshot)(nil), // 1: tokenbay.proto.v1.SignedBalanceSnapshot
}
var file_proto_balance_proto_depIdxs = []int32{
	0, // 0: tokenbay.proto.v1.SignedBalanceSnapshot.body:type_name -> tokenbay.proto.v1.BalanceSnapshotBody
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_balance_proto_init() }
func file_proto_balance_proto_init() {
	if File_proto_balance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_balance_proto_rawDesc), len(file_proto_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_balance_proto_goTypes,
		DependencyIndexes: file_proto_balance_proto_depIdxs,
		MessageInfos:      file_proto_balance_proto_msgTypes,
	}.Build()
	File_proto_balance_proto = out.File
	file_proto_balance_proto_goTypes = nil
	file_proto_balance_proto_depIdxs = nil
}
