// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/envelope.proto

package proto

import (
	exhaustionproof "github.com/token-bay/token-bay/shared/exhaustionproof"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PrivacyTier classifies a broker_request's confidentiality requirement.
// PRIVACY_TIER_UNSPECIFIED is rejected by ValidateEnvelopeBody.
type PrivacyTier int32

const (
	PrivacyTier_PRIVACY_TIER_UNSPECIFIED PrivacyTier = 0
	PrivacyTier_PRIVACY_TIER_STANDARD    PrivacyTier = 1
	PrivacyTier_PRIVACY_TIER_TEE         PrivacyTier = 2
)

// Enum value maps for PrivacyTier.
var (
	PrivacyTier_name = map[int32]string{
		0: "PRIVACY_TIER_UNSPECIFIED",
		1: "PRIVACY_TIER_STANDARD",
		2: "PRIVACY_TIER_TEE",
	}
	PrivacyTier_value = map[string]int32{
		"PRIVACY_TIER_UNSPECIFIED": 0,
		"PRIVACY_TIER_STANDARD":    1,
		"PRIVACY_TIER_TEE":         2,
	}
)

func (x PrivacyTier) Enum() *PrivacyTier {
	p := new(PrivacyTier)
	*p = x
	return p
}

func (x PrivacyTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrivacyTier) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_envelope_proto_enumTypes[0].Descriptor()
}

func (PrivacyTier) Type() protoreflect.EnumType {
	return &file_proto_envelope_proto_enumTypes[0]
}

func (x PrivacyTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrivacyTier.Descriptor instead.
func (PrivacyTier) EnumDescriptor() ([]byte, []int) {
	return file_proto_envelope_proto_rawDescGZIP(), []int{0}
}

// EnvelopeBody — the signed payload of a broker_request.
// Spec: docs/superpowers/specs/shared/2026-04-24-wire-format-v1-design.md §5.3.
// All consumer-side validation rules in ValidateEnvelopeBody (validate.go).
type EnvelopeBody struct {
	state           protoimpl.MessageState             `protogen:"open.v1"`
	ProtocolVersion uint32                             `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // matches shared/proto.ProtocolVersion
	ConsumerId      []byte                             `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`                 // 32 bytes — Ed25519 pubkey hash / IdentityID
	Model           string                             `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	MaxInputTokens  uint64                             `protobuf:"varint,4,opt,name=max_input_tokens,json=maxInputTokens,proto3" json:"max_input_tokens,omitempty"`
	MaxOutputTokens uint64                             `protobuf:"varint,5,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	Tier            PrivacyTier                        `protobuf:"varint,6,opt,name=tier,proto3,enum=tokenbay.proto.v1.PrivacyTier" json:"tier,omitempty"`
	BodyHash        []byte                             `protobuf:"bytes,7,opt,name=body_hash,json=bodyHash,proto3" json:"body_hash,omitempty"` // 32 bytes — SHA-256 of full Anthropic /v1/messages body
	ExhaustionProof *exhaustionproof.ExhaustionProofV1 `protobuf:"bytes,8,opt,name=exhaustion_proof,json=exhaustionProof,proto3" json:"exhaustion_proof,omitempty"`
	BalanceProof    *SignedBalanceSnapshot             `protobuf:"bytes,9,opt,name=balance_proof,json=balanceProof,proto3" json:"balance_proof,omitempty"`
	CapturedAt      uint64                             `protobuf:"varint,10,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"` // unix seconds — when envelope was assembled
	Nonce           []byte                             `protobuf:"bytes,11,opt,name=nonce,proto3" json:"nonce,omitempty"`                              // 16 bytes — envelope-level replay protection
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnvelopeBody) Reset() {
	*x = EnvelopeBody{}
	mi := &file_proto_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeBody) ProtoMessage() {}

func (x *EnvelopeBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeBody.ProtoReflect.Descriptor instead.
func (*EnvelopeBody) Descriptor() ([]byte, []int) {
	return file_proto_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *EnvelopeBody) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *EnvelopeBody) GetConsumerId() []byte {
	if x != nil {
		return x.ConsumerId
	}
	return nil
}

func (x *EnvelopeBody) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EnvelopeBody) GetMaxInputTokens() uint64 {
	if x != nil {
		return x.MaxInputTokens
	}
	return 0
}

func (x *EnvelopeBody) GetMaxOutputTokens() uint64 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *EnvelopeBody) GetTier() PrivacyTier {
	if x != nil {
		return x.Tier
	}
	return PrivacyTier_PRIVACY_TIER_UNSPECIFIED
}

func (x *EnvelopeBody) GetBodyHash() []byte {
	if x != nil {
		return x.BodyHash
	}
	return nil
}

func (x *EnvelopeBody) GetExhaustionProof() *exhaustionproof.ExhaustionProofV1 {
	if x != nil {
		return x.ExhaustionProof
	}
	return nil
}

func (x *EnvelopeBody) GetBalanceProof() *SignedBalanceSnapshot {
	if x != nil {
		return x.BalanceProof
	}
	return nil
}

func (x *EnvelopeBody) GetCapturedAt() uint64 {
	if x != nil {
		return x.CapturedAt
	}
	return 0
}

func (x *EnvelopeBody) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

// EnvelopeSigned — wire form. Receiver verifies sig via
// shared/signing.VerifyEnvelope (Task 7).
type EnvelopeSigned struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *EnvelopeBody          `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	ConsumerSig   []byte                 `protobuf:"bytes,2,opt,name=consumer_sig,json=consumerSig,proto3" json:"consumer_sig,omitempty"` // 64 bytes — Ed25519 over DeterministicMarshal(body)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvelopeSigned) Reset() {
	*x = EnvelopeSigned{}
	mi := &file_proto_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeSigned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeSigned) ProtoMessage() {}

func (x *EnvelopeSigned) ProtoReflect() protoreflect.Message {
	mi := &file_proto_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeSigned.ProtoReflect.Descriptor instead.
func (*EnvelopeSigned) Descriptor() ([]byte, []int) {
	return file_proto_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *EnvelopeSigned) GetBody() *EnvelopeBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *EnvelopeSigned) GetConsumerSig() []byte {
	if x != nil {
		return x.ConsumerSig
	}
	return nil
}

var File_proto_envelope_proto protoreflect.FileDescriptor

const file_proto_envelope_proto_rawDesc = "" +
	"\n" +
	"\x14proto/envelope.proto\x12\x11tokenbay.proto.v1\x1a\x1bexhaustionproof/proof.proto\x1a\x13proto/balance.proto\"\xf8\x03\n" +
	"\fEnvelopeBody\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\fR\n" +
	"consumerId\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12(\n" +
	"\x10max_input_tokens\x18\x04 \x01(\x04R\x0emaxInputTokens\x12*\n" +
	"\x11max_output_tokens\x18\x05 \x01(\x04R\x0fmaxOutputTokens\x122\n" +
	"\x04tier\x18\x06 \x01(\x0e2\x1e.tokenbay.proto.v1.PrivacyTierR\x04tier\x12\x1b\n" +
	"\tbody_hash\x18\a \x01(\fR\bbodyHash\x12Y\n" +
	"\x10exhaustion_proof\x18\b \x01(\v2..tokenbay.exhaustionproof.v1.ExhaustionProofV1R\x0fexhaustionProof\x12M\n" +
	"\rbalance_proof\x18\t \x01(\v2(.tokenbay.proto.v1.SignedBalanceSnapshotR\fbalanceProof\x12\x1f\n" +
	"\vcaptured_at\x18\n" +
	" \x01(\x04R\n" +
	"capturedAt\x12\x14\n" +
	"\x05nonce\x18\v \x01(\fR\x05nonce\"h\n" +
	"\x0eEnvelopeSigned\x123\n" +
	"\x04body\x18\x01 \x01(\v2\x1f.tokenbay.proto.v1.EnvelopeBodyR\x04body\x12!\n" +
	"\fconsumer_sig\x18\x02 \x01(\fR\vconsumerSig*\\\n" +
	"\vPrivacyTier\x12\x1c\n" +
	"\x18PRIVACY_TIER_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PRIVACY_TIER_STANDARD\x10\x01\x12\x14\n" +
	"\x10PRIVACY_TIER_TEE\x10\x02B-Z+github.com/token-bay/token-bay/shared/protob\x06proto3"

var (
	file_proto_envelope_proto_rawDescOnce sync.Once
	file_proto_envelope_proto_rawDescData []byte
)

func file_proto_envelope_proto_rawDescGZIP() []byte {
	file_proto_envelope_proto_rawDescOnce.Do(func() {
		file_proto_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_envelope_proto_rawDesc), len(file_proto_envelope_proto_rawDesc)))
	})
	return file_proto_envelope_proto_rawDescData
}

var file_proto_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_envelope_proto_goTypes = []any{
	(PrivacyTier)(0),                          // 0: tokenbay.proto.v1.PrivacyTier
	(*EnvelopeBody)(nil),                      // 1: tokenbay.proto.v1.EnvelopeBody
	(*EnvelopeSigned)(nil),                    // 2: tokenbay.proto.v1.EnvelopeSigned
	(*exhaustionproof.ExhaustionProofV1)(nil), // 3: tokenbay.exhaustionproof.v1.ExhaustionProofV1
	(*SignedBalanceSnapshot)(nil),             // 4: tokenbay.proto.v1.SignedBalanceSnapshot
}
var file_proto_envelope_proto_depIdxs = []int32{
	0, // 0: tokenbay.proto.v1.EnvelopeBody.tier:type_name -> tokenbay.proto.v1.PrivacyTier
	3, // 1: tokenbay.proto.v1.EnvelopeBody.exhaustion_proof:type_name -> tokenbay.exhaustionproof.v1.ExhaustionProofV1
	4, // 2: tokenbay.proto.v1.EnvelopeBody.balance_proof:type_name -> tokenbay.proto.v1.SignedBalanceSnapshot
	1, // 3: tokenbay.proto.v1.EnvelopeSigned.body:type_name -> tokenbay.proto.v1.EnvelopeBody
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_envelope_proto_init() }
func file_proto_envelope_proto_init() {
	if File_proto_envelope_proto != nil {
		return
	}
	file_proto_balance_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_envelope_proto_rawDesc), len(file_proto_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_envelope_proto_goTypes,
		DependencyIndexes: file_proto_envelope_proto_depIdxs,
		EnumInfos:         file_proto_envelope_proto_enumTypes,
		MessageInfos:      file_proto_envelope_proto_msgTypes,
	}.Build()
	File_proto_envelope_proto = out.File
	file_proto_envelope_proto_goTypes = nil
	file_proto_envelope_proto_depIdxs = nil
}
