// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ledger.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntryKind classifies a ledger entry's semantic role.
// ENTRY_KIND_UNSPECIFIED is rejected by ValidateEntryBody.
type EntryKind int32

const (
	EntryKind_ENTRY_KIND_UNSPECIFIED   EntryKind = 0
	EntryKind_ENTRY_KIND_USAGE         EntryKind = 1
	EntryKind_ENTRY_KIND_TRANSFER_OUT  EntryKind = 2
	EntryKind_ENTRY_KIND_TRANSFER_IN   EntryKind = 3
	EntryKind_ENTRY_KIND_STARTER_GRANT EntryKind = 4
)

// Enum value maps for EntryKind.
var (
	EntryKind_name = map[int32]string{
		0: "ENTRY_KIND_UNSPECIFIED",
		1: "ENTRY_KIND_USAGE",
		2: "ENTRY_KIND_TRANSFER_OUT",
		3: "ENTRY_KIND_TRANSFER_IN",
		4: "ENTRY_KIND_STARTER_GRANT",
	}
	EntryKind_value = map[string]int32{
		"ENTRY_KIND_UNSPECIFIED":   0,
		"ENTRY_KIND_USAGE":         1,
		"ENTRY_KIND_TRANSFER_OUT":  2,
		"ENTRY_KIND_TRANSFER_IN":   3,
		"ENTRY_KIND_STARTER_GRANT": 4,
	}
)

func (x EntryKind) Enum() *EntryKind {
	p := new(EntryKind)
	*p = x
	return p
}

func (x EntryKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ledger_proto_enumTypes[0].Descriptor()
}

func (EntryKind) Type() protoreflect.EnumType {
	return &file_proto_ledger_proto_enumTypes[0]
}

func (x EntryKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryKind.Descriptor instead.
func (EntryKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{0}
}

// EntryBody — the signed payload of a ledger entry.
// Spec: docs/superpowers/specs/ledger/2026-04-22-ledger-design.md §3.1.
// All three signatures (consumer/seeder/tracker) are computed over
// shared/signing.DeterministicMarshal(body).
type EntryBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrevHash      []byte                 `protobuf:"bytes,1,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"` // 32 bytes; zero for genesis
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Kind          EntryKind              `protobuf:"varint,3,opt,name=kind,proto3,enum=tokenbay.proto.v1.EntryKind" json:"kind,omitempty"`
	ConsumerId    []byte                 `protobuf:"bytes,4,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`        // 32 bytes; zero for transfer_in/transfer_out (peer-side)
	SeederId      []byte                 `protobuf:"bytes,5,opt,name=seeder_id,json=seederId,proto3" json:"seeder_id,omitempty"`              // 32 bytes; zero for non-usage kinds
	Model         string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`                                    // "" for non-usage kinds
	InputTokens   uint32                 `protobuf:"varint,7,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`    // 0 for non-usage kinds
	OutputTokens  uint32                 `protobuf:"varint,8,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"` // 0 for non-usage kinds
	CostCredits   uint64                 `protobuf:"varint,9,opt,name=cost_credits,json=costCredits,proto3" json:"cost_credits,omitempty"`    // absolute value; sign determined by kind+party
	Timestamp     uint64                 `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                          // unix seconds
	RequestId     []byte                 `protobuf:"bytes,11,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`          // 16 bytes (UUID); zero for non-usage kinds
	Flags         uint32                 `protobuf:"varint,12,opt,name=flags,proto3" json:"flags,omitempty"`                                  // bit 0 = consumer_sig_missing
	Ref           []byte                 `protobuf:"bytes,13,opt,name=ref,proto3" json:"ref,omitempty"`                                       // 32 bytes; transfer UUID for transfer_*; zero otherwise
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryBody) Reset() {
	*x = EntryBody{}
	mi := &file_proto_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryBody) ProtoMessage() {}

func (x *EntryBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryBody.ProtoReflect.Descriptor instead.
func (*EntryBody) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *EntryBody) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *EntryBody) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EntryBody) GetKind() EntryKind {
	if x != nil {
		return x.Kind
	}
	return EntryKind_ENTRY_KIND_UNSPECIFIED
}

func (x *EntryBody) GetConsumerId() []byte {
	if x != nil {
		return x.ConsumerId
	}
	return nil
}

func (x *EntryBody) GetSeederId() []byte {
	if x != nil {
		return x.SeederId
	}
	return nil
}

func (x *EntryBody) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EntryBody) GetInputTokens() uint32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *EntryBody) GetOutputTokens() uint32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *EntryBody) GetCostCredits() uint64 {
	if x != nil {
		return x.CostCredits
	}
	return 0
}

func (x *EntryBody) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *EntryBody) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *EntryBody) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *EntryBody) GetRef() []byte {
	if x != nil {
		return x.Ref
	}
	return nil
}

// Entry — wire form. Receiver verifies signatures via
// shared/signing.VerifyEntry plus tracker entry.VerifyAll.
type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *EntryBody             `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	ConsumerSig   []byte                 `protobuf:"bytes,2,opt,name=consumer_sig,json=consumerSig,proto3" json:"consumer_sig,omitempty"` // 64 bytes or empty per per-kind matrix
	SeederSig     []byte                 `protobuf:"bytes,3,opt,name=seeder_sig,json=seederSig,proto3" json:"seeder_sig,omitempty"`       // 64 bytes or empty per per-kind matrix
	TrackerSig    []byte                 `protobuf:"bytes,4,opt,name=tracker_sig,json=trackerSig,proto3" json:"tracker_sig,omitempty"`    // 64 bytes; mandatory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_proto_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_proto_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetBody() *EntryBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Entry) GetConsumerSig() []byte {
	if x != nil {
		return x.ConsumerSig
	}
	return nil
}

func (x *Entry) GetSeederSig() []byte {
	if x != nil {
		return x.SeederSig
	}
	return nil
}

func (x *Entry) GetTrackerSig() []byte {
	if x != nil {
		return x.TrackerSig
	}
	return nil
}

var File_proto_ledger_proto protoreflect.FileDescriptor

const file_proto_ledger_proto_rawDesc = "" +
	"\n" +
	"\x12proto/ledger.proto\x12\x11tokenbay.proto.v1\"\x90\x03\n" +
	"\tEntryBody\x12\x1b\n" +
	"\tprev_hash\x18\x01 \x01(\fR\bprevHash\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x120\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1c.tokenbay.proto.v1.EntryKindR\x04kind\x12\x1f\n" +
	"\vconsumer_id\x18\x04 \x01(\fR\n" +
	"consumerId\x12\x1b\n" +
	"\tseeder_id\x18\x05 \x01(\fR\bseederId\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12!\n" +
	"\finput_tokens\x18\a \x01(\rR\vinputTokens\x12#\n" +
	"\routput_tokens\x18\b \x01(\rR\foutputTokens\x12!\n" +
	"\fcost_credits\x18\t \x01(\x04R\vcostCredits\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x04R\ttimestamp\x12\x1d\n" +
	"\n" +
	"request_id\x18\v \x01(\fR\trequestId\x12\x14\n" +
	"\x05flags\x18\f \x01(\rR\x05flags\x12\x10\n" +
	"\x03ref\x18\r \x01(\fR\x03ref\"\x9c\x01\n" +
	"\x05Entry\x120\n" +
	"\x04body\x18\x01 \x01(\v2\x1c.tokenbay.proto.v1.EntryBodyR\x04body\x12!\n" +
	"\fconsumer_sig\x18\x02 \x01(\fR\vconsumerSig\x12\x1d\n" +
	"\n" +
	"seeder_sig\x18\x03 \x01(\fR\tseederSig\x12\x1f\n" +
	"\vtracker_sig\x18\x04 \x01(\fR\n" +
	"trackerSig*\x94\x01\n" +
	"\tEntryKind\x12\x1a\n" +
	"\x16ENTRY_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ENTRY_KIND_USAGE\x10\x01\x12\x1b\n" +
	"\x17ENTRY_KIND_TRANSFER_OUT\x10\x02\x12\x1a\n" +
	"\x16ENTRY_KIND_TRANSFER_IN\x10\x03\x12\x1c\n" +
	"\x18ENTRY_KIND_STARTER_GRANT\x10\x04B-Z+github.com/token-bay/token-bay/shared/protob\x06proto3"

var (
	file_proto_ledger_proto_rawDescOnce sync.Once
	file_proto_ledger_proto_rawDescData []byte
)

func file_proto_ledger_proto_rawDescGZIP() []byte {
	file_proto_ledger_proto_rawDescOnce.Do(func() {
		file_proto_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ledger_proto_rawDesc), len(file_proto_ledger_proto_rawDesc)))
	})
	return file_proto_ledger_proto_rawDescData
}

var file_proto_ledger_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ledger_proto_goTypes = []any{
	(EntryKind)(0),    // 0: tokenbay.proto.v1.EntryKind
	(*EntryBody)(nil), // 1: tokenbay.proto.v1.EntryBody
	(*Entry)(nil),     // 2: tokenbay.proto.v1.Entry
}
var file_proto_ledger_proto_depIdxs = []int32{
	0, // 0: tokenbay.proto.v1.EntryBody.kind:type_name -> tokenbay.proto.v1.EntryKind
	1, // 1: tokenbay.proto.v1.Entry.body:type_name -> tokenbay.proto.v1.EntryBody
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ledger_proto_init() }
func file_proto_ledger_proto_init() {
	if File_proto_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ledger_proto_rawDesc), len(file_proto_ledger_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ledger_proto_goTypes,
		DependencyIndexes: file_proto_ledger_proto_depIdxs,
		EnumInfos:         file_proto_ledger_proto_enumTypes,
		MessageInfos:      file_proto_ledger_proto_msgTypes,
	}.Build()
	File_proto_ledger_proto = out.File
	file_proto_ledger_proto_goTypes = nil
	file_proto_ledger_proto_depIdxs = nil
}
