// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/rpc.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RpcMethod identifies the unary RPC the client is invoking.
//
// Method 0 (RPC_METHOD_UNSPECIFIED) is reserved as the heartbeat-channel
// marker on the dedicated heartbeat stream — it is NOT an "unset" sentinel.
// Validators reject method 0 on regular RPC streams.
type RpcMethod int32

const (
	RpcMethod_RPC_METHOD_UNSPECIFIED      RpcMethod = 0 // heartbeat-channel marker
	RpcMethod_RPC_METHOD_ENROLL           RpcMethod = 1
	RpcMethod_RPC_METHOD_BROKER_REQUEST   RpcMethod = 2
	RpcMethod_RPC_METHOD_BALANCE          RpcMethod = 3
	RpcMethod_RPC_METHOD_SETTLE           RpcMethod = 4
	RpcMethod_RPC_METHOD_USAGE_REPORT     RpcMethod = 5
	RpcMethod_RPC_METHOD_ADVERTISE        RpcMethod = 6
	RpcMethod_RPC_METHOD_TRANSFER_REQUEST RpcMethod = 7
	RpcMethod_RPC_METHOD_STUN_ALLOCATE    RpcMethod = 8
	RpcMethod_RPC_METHOD_TURN_RELAY_OPEN  RpcMethod = 9
	RpcMethod_RPC_METHOD_BOOTSTRAP_PEERS  RpcMethod = 10
)

// Enum value maps for RpcMethod.
var (
	RpcMethod_name = map[int32]string{
		0:  "RPC_METHOD_UNSPECIFIED",
		1:  "RPC_METHOD_ENROLL",
		2:  "RPC_METHOD_BROKER_REQUEST",
		3:  "RPC_METHOD_BALANCE",
		4:  "RPC_METHOD_SETTLE",
		5:  "RPC_METHOD_USAGE_REPORT",
		6:  "RPC_METHOD_ADVERTISE",
		7:  "RPC_METHOD_TRANSFER_REQUEST",
		8:  "RPC_METHOD_STUN_ALLOCATE",
		9:  "RPC_METHOD_TURN_RELAY_OPEN",
		10: "RPC_METHOD_BOOTSTRAP_PEERS",
	}
	RpcMethod_value = map[string]int32{
		"RPC_METHOD_UNSPECIFIED":      0,
		"RPC_METHOD_ENROLL":           1,
		"RPC_METHOD_BROKER_REQUEST":   2,
		"RPC_METHOD_BALANCE":          3,
		"RPC_METHOD_SETTLE":           4,
		"RPC_METHOD_USAGE_REPORT":     5,
		"RPC_METHOD_ADVERTISE":        6,
		"RPC_METHOD_TRANSFER_REQUEST": 7,
		"RPC_METHOD_STUN_ALLOCATE":    8,
		"RPC_METHOD_TURN_RELAY_OPEN":  9,
		"RPC_METHOD_BOOTSTRAP_PEERS":  10,
	}
)

func (x RpcMethod) Enum() *RpcMethod {
	p := new(RpcMethod)
	*p = x
	return p
}

func (x RpcMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rpc_proto_enumTypes[0].Descriptor()
}

func (RpcMethod) Type() protoreflect.EnumType {
	return &file_proto_rpc_proto_enumTypes[0]
}

func (x RpcMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcMethod.Descriptor instead.
func (RpcMethod) EnumDescriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{0}
}

type RpcStatus int32

const (
	RpcStatus_RPC_STATUS_UNSPECIFIED     RpcStatus = 0
	RpcStatus_RPC_STATUS_OK              RpcStatus = 1
	RpcStatus_RPC_STATUS_INVALID         RpcStatus = 2
	RpcStatus_RPC_STATUS_NO_CAPACITY     RpcStatus = 3
	RpcStatus_RPC_STATUS_FROZEN          RpcStatus = 4
	RpcStatus_RPC_STATUS_INTERNAL        RpcStatus = 5
	RpcStatus_RPC_STATUS_UNAUTHENTICATED RpcStatus = 6
	RpcStatus_RPC_STATUS_NOT_FOUND       RpcStatus = 7
)

// Enum value maps for RpcStatus.
var (
	RpcStatus_name = map[int32]string{
		0: "RPC_STATUS_UNSPECIFIED",
		1: "RPC_STATUS_OK",
		2: "RPC_STATUS_INVALID",
		3: "RPC_STATUS_NO_CAPACITY",
		4: "RPC_STATUS_FROZEN",
		5: "RPC_STATUS_INTERNAL",
		6: "RPC_STATUS_UNAUTHENTICATED",
		7: "RPC_STATUS_NOT_FOUND",
	}
	RpcStatus_value = map[string]int32{
		"RPC_STATUS_UNSPECIFIED":     0,
		"RPC_STATUS_OK":              1,
		"RPC_STATUS_INVALID":         2,
		"RPC_STATUS_NO_CAPACITY":     3,
		"RPC_STATUS_FROZEN":          4,
		"RPC_STATUS_INTERNAL":        5,
		"RPC_STATUS_UNAUTHENTICATED": 6,
		"RPC_STATUS_NOT_FOUND":       7,
	}
)

func (x RpcStatus) Enum() *RpcStatus {
	p := new(RpcStatus)
	*p = x
	return p
}

func (x RpcStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rpc_proto_enumTypes[1].Descriptor()
}

func (RpcStatus) Type() protoreflect.EnumType {
	return &file_proto_rpc_proto_enumTypes[1]
}

func (x RpcStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcStatus.Descriptor instead.
func (RpcStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{1}
}

type PositionBand int32

const (
	PositionBand_POSITION_BAND_UNSPECIFIED PositionBand = 0
	PositionBand_POSITION_BAND_1_TO_10     PositionBand = 1
	PositionBand_POSITION_BAND_11_TO_50    PositionBand = 2
	PositionBand_POSITION_BAND_51_TO_200   PositionBand = 3
	PositionBand_POSITION_BAND_200_PLUS    PositionBand = 4
)

// Enum value maps for PositionBand.
var (
	PositionBand_name = map[int32]string{
		0: "POSITION_BAND_UNSPECIFIED",
		1: "POSITION_BAND_1_TO_10",
		2: "POSITION_BAND_11_TO_50",
		3: "POSITION_BAND_51_TO_200",
		4: "POSITION_BAND_200_PLUS",
	}
	PositionBand_value = map[string]int32{
		"POSITION_BAND_UNSPECIFIED": 0,
		"POSITION_BAND_1_TO_10":     1,
		"POSITION_BAND_11_TO_50":    2,
		"POSITION_BAND_51_TO_200":   3,
		"POSITION_BAND_200_PLUS":    4,
	}
)

func (x PositionBand) Enum() *PositionBand {
	p := new(PositionBand)
	*p = x
	return p
}

func (x PositionBand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PositionBand) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rpc_proto_enumTypes[2].Descriptor()
}

func (PositionBand) Type() protoreflect.EnumType {
	return &file_proto_rpc_proto_enumTypes[2]
}

func (x PositionBand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PositionBand.Descriptor instead.
func (PositionBand) EnumDescriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{2}
}

type EtaBand int32

const (
	EtaBand_ETA_BAND_UNSPECIFIED EtaBand = 0
	EtaBand_ETA_BAND_LT_30S      EtaBand = 1
	EtaBand_ETA_BAND_30S_TO_2M   EtaBand = 2
	EtaBand_ETA_BAND_2M_TO_5M    EtaBand = 3
	EtaBand_ETA_BAND_5M_PLUS     EtaBand = 4
)

// Enum value maps for EtaBand.
var (
	EtaBand_name = map[int32]string{
		0: "ETA_BAND_UNSPECIFIED",
		1: "ETA_BAND_LT_30S",
		2: "ETA_BAND_30S_TO_2M",
		3: "ETA_BAND_2M_TO_5M",
		4: "ETA_BAND_5M_PLUS",
	}
	EtaBand_value = map[string]int32{
		"ETA_BAND_UNSPECIFIED": 0,
		"ETA_BAND_LT_30S":      1,
		"ETA_BAND_30S_TO_2M":   2,
		"ETA_BAND_2M_TO_5M":    3,
		"ETA_BAND_5M_PLUS":     4,
	}
)

func (x EtaBand) Enum() *EtaBand {
	p := new(EtaBand)
	*p = x
	return p
}

func (x EtaBand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EtaBand) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rpc_proto_enumTypes[3].Descriptor()
}

func (EtaBand) Type() protoreflect.EnumType {
	return &file_proto_rpc_proto_enumTypes[3]
}

func (x EtaBand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EtaBand.Descriptor instead.
func (EtaBand) EnumDescriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{3}
}

type RejectReason int32

const (
	RejectReason_REJECT_REASON_UNSPECIFIED       RejectReason = 0
	RejectReason_REJECT_REASON_REGION_OVERLOADED RejectReason = 1
	RejectReason_REJECT_REASON_QUEUE_TIMEOUT     RejectReason = 2
)

// Enum value maps for RejectReason.
var (
	RejectReason_name = map[int32]string{
		0: "REJECT_REASON_UNSPECIFIED",
		1: "REJECT_REASON_REGION_OVERLOADED",
		2: "REJECT_REASON_QUEUE_TIMEOUT",
	}
	RejectReason_value = map[string]int32{
		"REJECT_REASON_UNSPECIFIED":       0,
		"REJECT_REASON_REGION_OVERLOADED": 1,
		"REJECT_REASON_QUEUE_TIMEOUT":     2,
	}
)

func (x RejectReason) Enum() *RejectReason {
	p := new(RejectReason)
	*p = x
	return p
}

func (x RejectReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RejectReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rpc_proto_enumTypes[4].Descriptor()
}

func (RejectReason) Type() protoreflect.EnumType {
	return &file_proto_rpc_proto_enumTypes[4]
}

func (x RejectReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RejectReason.Descriptor instead.
func (RejectReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{4}
}

type RpcError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcError) Reset() {
	*x = RpcError{}
	mi := &file_proto_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcError) ProtoMessage() {}

func (x *RpcError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcError.ProtoReflect.Descriptor instead.
func (*RpcError) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RpcError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RpcError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        RpcMethod              `protobuf:"varint,1,opt,name=method,proto3,enum=tokenbay.proto.v1.RpcMethod" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	mi := &file_proto_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RpcRequest) GetMethod() RpcMethod {
	if x != nil {
		return x.Method
	}
	return RpcMethod_RPC_METHOD_UNSPECIFIED
}

func (x *RpcRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        RpcStatus              `protobuf:"varint,1,opt,name=status,proto3,enum=tokenbay.proto.v1.RpcStatus" json:"status,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         *RpcError              `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	mi := &file_proto_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RpcResponse) GetStatus() RpcStatus {
	if x != nil {
		return x.Status
	}
	return RpcStatus_RPC_STATUS_UNSPECIFIED
}

func (x *RpcResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RpcResponse) GetError() *RpcError {
	if x != nil {
		return x.Error
	}
	return nil
}

type EnrollRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IdentityPubkey     []byte                 `protobuf:"bytes,1,opt,name=identity_pubkey,json=identityPubkey,proto3" json:"identity_pubkey,omitempty"`             // 32
	Role               uint32                 `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`                                                      // bit0: consumer, bit1: seeder
	AccountFingerprint []byte                 `protobuf:"bytes,3,opt,name=account_fingerprint,json=accountFingerprint,proto3" json:"account_fingerprint,omitempty"` // 32 — SHA-256(orgId)
	Nonce              []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`                                                     // 16
	ConsumerSig        []byte                 `protobuf:"bytes,5,opt,name=consumer_sig,json=consumerSig,proto3" json:"consumer_sig,omitempty"`                      // 64
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_proto_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *EnrollRequest) GetIdentityPubkey() []byte {
	if x != nil {
		return x.IdentityPubkey
	}
	return nil
}

func (x *EnrollRequest) GetRole() uint32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *EnrollRequest) GetAccountFingerprint() []byte {
	if x != nil {
		return x.AccountFingerprint
	}
	return nil
}

func (x *EnrollRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EnrollRequest) GetConsumerSig() []byte {
	if x != nil {
		return x.ConsumerSig
	}
	return nil
}

type EnrollResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IdentityId          []byte                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"` // 32
	StarterGrantCredits uint64                 `protobuf:"varint,2,opt,name=starter_grant_credits,json=starterGrantCredits,proto3" json:"starter_grant_credits,omitempty"`
	StarterGrantEntry   []byte                 `protobuf:"bytes,3,opt,name=starter_grant_entry,json=starterGrantEntry,proto3" json:"starter_grant_entry,omitempty"` // serialized EntrySigned
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_proto_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *EnrollResponse) GetIdentityId() []byte {
	if x != nil {
		return x.IdentityId
	}
	return nil
}

func (x *EnrollResponse) GetStarterGrantCredits() uint64 {
	if x != nil {
		return x.StarterGrantCredits
	}
	return 0
}

func (x *EnrollResponse) GetStarterGrantEntry() []byte {
	if x != nil {
		return x.StarterGrantEntry
	}
	return nil
}

type SeederAssignment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SeederAddr       []byte                 `protobuf:"bytes,1,opt,name=seeder_addr,json=seederAddr,proto3" json:"seeder_addr,omitempty"`                   // utf-8 host:port
	SeederPubkey     []byte                 `protobuf:"bytes,2,opt,name=seeder_pubkey,json=seederPubkey,proto3" json:"seeder_pubkey,omitempty"`             // 32
	ReservationToken []byte                 `protobuf:"bytes,3,opt,name=reservation_token,json=reservationToken,proto3" json:"reservation_token,omitempty"` // 16 bytes — equals request_id
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SeederAssignment) Reset() {
	*x = SeederAssignment{}
	mi := &file_proto_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeederAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeederAssignment) ProtoMessage() {}

func (x *SeederAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeederAssignment.ProtoReflect.Descriptor instead.
func (*SeederAssignment) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *SeederAssignment) GetSeederAddr() []byte {
	if x != nil {
		return x.SeederAddr
	}
	return nil
}

func (x *SeederAssignment) GetSeederPubkey() []byte {
	if x != nil {
		return x.SeederPubkey
	}
	return nil
}

func (x *SeederAssignment) GetReservationToken() []byte {
	if x != nil {
		return x.ReservationToken
	}
	return nil
}

type NoCapacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoCapacity) Reset() {
	*x = NoCapacity{}
	mi := &file_proto_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoCapacity) ProtoMessage() {}

func (x *NoCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoCapacity.ProtoReflect.Descriptor instead.
func (*NoCapacity) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *NoCapacity) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Queued struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     []byte                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 16
	PositionBand  PositionBand           `protobuf:"varint,2,opt,name=position_band,json=positionBand,proto3,enum=tokenbay.proto.v1.PositionBand" json:"position_band,omitempty"`
	EtaBand       EtaBand                `protobuf:"varint,3,opt,name=eta_band,json=etaBand,proto3,enum=tokenbay.proto.v1.EtaBand" json:"eta_band,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Queued) Reset() {
	*x = Queued{}
	mi := &file_proto_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queued) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queued) ProtoMessage() {}

func (x *Queued) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queued.ProtoReflect.Descriptor instead.
func (*Queued) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *Queued) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *Queued) GetPositionBand() PositionBand {
	if x != nil {
		return x.PositionBand
	}
	return PositionBand_POSITION_BAND_UNSPECIFIED
}

func (x *Queued) GetEtaBand() EtaBand {
	if x != nil {
		return x.EtaBand
	}
	return EtaBand_ETA_BAND_UNSPECIFIED
}

type Rejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        RejectReason           `protobuf:"varint,1,opt,name=reason,proto3,enum=tokenbay.proto.v1.RejectReason" json:"reason,omitempty"`
	RetryAfterS   uint32                 `protobuf:"varint,2,opt,name=retry_after_s,json=retryAfterS,proto3" json:"retry_after_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rejected) Reset() {
	*x = Rejected{}
	mi := &file_proto_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rejected) ProtoMessage() {}

func (x *Rejected) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rejected.ProtoReflect.Descriptor instead.
func (*Rejected) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *Rejected) GetReason() RejectReason {
	if x != nil {
		return x.Reason
	}
	return RejectReason_REJECT_REASON_UNSPECIFIED
}

func (x *Rejected) GetRetryAfterS() uint32 {
	if x != nil {
		return x.RetryAfterS
	}
	return 0
}

type BrokerRequestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*BrokerRequestResponse_SeederAssignment
	//	*BrokerRequestResponse_NoCapacity
	//	*BrokerRequestResponse_Queued
	//	*BrokerRequestResponse_Rejected
	Outcome       isBrokerRequestResponse_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokerRequestResponse) Reset() {
	*x = BrokerRequestResponse{}
	mi := &file_proto_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerRequestResponse) ProtoMessage() {}

func (x *BrokerRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerRequestResponse.ProtoReflect.Descriptor instead.
func (*BrokerRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *BrokerRequestResponse) GetOutcome() isBrokerRequestResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *BrokerRequestResponse) GetSeederAssignment() *SeederAssignment {
	if x != nil {
		if x, ok := x.Outcome.(*BrokerRequestResponse_SeederAssignment); ok {
			return x.SeederAssignment
		}
	}
	return nil
}

func (x *BrokerRequestResponse) GetNoCapacity() *NoCapacity {
	if x != nil {
		if x, ok := x.Outcome.(*BrokerRequestResponse_NoCapacity); ok {
			return x.NoCapacity
		}
	}
	return nil
}

func (x *BrokerRequestResponse) GetQueued() *Queued {
	if x != nil {
		if x, ok := x.Outcome.(*BrokerRequestResponse_Queued); ok {
			return x.Queued
		}
	}
	return nil
}

func (x *BrokerRequestResponse) GetRejected() *Rejected {
	if x != nil {
		if x, ok := x.Outcome.(*BrokerRequestResponse_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

type isBrokerRequestResponse_Outcome interface {
	isBrokerRequestResponse_Outcome()
}

type BrokerRequestResponse_SeederAssignment struct {
	SeederAssignment *SeederAssignment `protobuf:"bytes,1,opt,name=seeder_assignment,json=seederAssignment,proto3,oneof"`
}

type BrokerRequestResponse_NoCapacity struct {
	NoCapacity *NoCapacity `protobuf:"bytes,2,opt,name=no_capacity,json=noCapacity,proto3,oneof"`
}

type BrokerRequestResponse_Queued struct {
	Queued *Queued `protobuf:"bytes,3,opt,name=queued,proto3,oneof"`
}

type BrokerRequestResponse_Rejected struct {
	Rejected *Rejected `protobuf:"bytes,4,opt,name=rejected,proto3,oneof"`
}

func (*BrokerRequestResponse_SeederAssignment) isBrokerRequestResponse_Outcome() {}

func (*BrokerRequestResponse_NoCapacity) isBrokerRequestResponse_Outcome() {}

func (*BrokerRequestResponse_Queued) isBrokerRequestResponse_Outcome() {}

func (*BrokerRequestResponse_Rejected) isBrokerRequestResponse_Outcome() {}

type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    []byte                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"` // 32
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_proto_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *BalanceRequest) GetIdentityId() []byte {
	if x != nil {
		return x.IdentityId
	}
	return nil
}

type SettleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreimageHash  []byte                 `protobuf:"bytes,1,opt,name=preimage_hash,json=preimageHash,proto3" json:"preimage_hash,omitempty"` // 32
	ConsumerSig   []byte                 `protobuf:"bytes,2,opt,name=consumer_sig,json=consumerSig,proto3" json:"consumer_sig,omitempty"`    // 64
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleRequest) Reset() {
	*x = SettleRequest{}
	mi := &file_proto_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleRequest) ProtoMessage() {}

func (x *SettleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleRequest.ProtoReflect.Descriptor instead.
func (*SettleRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *SettleRequest) GetPreimageHash() []byte {
	if x != nil {
		return x.PreimageHash
	}
	return nil
}

func (x *SettleRequest) GetConsumerSig() []byte {
	if x != nil {
		return x.ConsumerSig
	}
	return nil
}

type SettleAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleAck) Reset() {
	*x = SettleAck{}
	mi := &file_proto_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleAck) ProtoMessage() {}

func (x *SettleAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleAck.ProtoReflect.Descriptor instead.
func (*SettleAck) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{12}
}

type UsageReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     []byte                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 16 — uuid
	InputTokens   uint32                 `protobuf:"varint,2,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  uint32                 `protobuf:"varint,3,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	SeederSig     []byte                 `protobuf:"bytes,5,opt,name=seeder_sig,json=seederSig,proto3" json:"seeder_sig,omitempty"` // 64
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageReport) Reset() {
	*x = UsageReport{}
	mi := &file_proto_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageReport) ProtoMessage() {}

func (x *UsageReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageReport.ProtoReflect.Descriptor instead.
func (*UsageReport) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *UsageReport) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *UsageReport) GetInputTokens() uint32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *UsageReport) GetOutputTokens() uint32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *UsageReport) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UsageReport) GetSeederSig() []byte {
	if x != nil {
		return x.SeederSig
	}
	return nil
}

type UsageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageAck) Reset() {
	*x = UsageAck{}
	mi := &file_proto_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageAck) ProtoMessage() {}

func (x *UsageAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageAck.ProtoReflect.Descriptor instead.
func (*UsageAck) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{14}
}

type Advertisement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []string               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	MaxContext    uint32                 `protobuf:"varint,2,opt,name=max_context,json=maxContext,proto3" json:"max_context,omitempty"`
	Available     bool                   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	Headroom      float32                `protobuf:"fixed32,4,opt,name=headroom,proto3" json:"headroom,omitempty"`
	Tiers         uint32                 `protobuf:"varint,5,opt,name=tiers,proto3" json:"tiers,omitempty"` // bitmask: bit0 standard, bit1 tee
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Advertisement) Reset() {
	*x = Advertisement{}
	mi := &file_proto_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Advertisement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Advertisement) ProtoMessage() {}

func (x *Advertisement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Advertisement.ProtoReflect.Descriptor instead.
func (*Advertisement) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *Advertisement) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *Advertisement) GetMaxContext() uint32 {
	if x != nil {
		return x.MaxContext
	}
	return 0
}

func (x *Advertisement) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *Advertisement) GetHeadroom() float32 {
	if x != nil {
		return x.Headroom
	}
	return 0
}

func (x *Advertisement) GetTiers() uint32 {
	if x != nil {
		return x.Tiers
	}
	return 0
}

type AdvertiseAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvertiseAck) Reset() {
	*x = AdvertiseAck{}
	mi := &file_proto_rpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvertiseAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvertiseAck) ProtoMessage() {}

func (x *AdvertiseAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvertiseAck.ProtoReflect.Descriptor instead.
func (*AdvertiseAck) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{16}
}

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    []byte                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	DestRegion    string                 `protobuf:"bytes,3,opt,name=dest_region,json=destRegion,proto3" json:"dest_region,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_proto_rpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{17}
}

func (x *TransferRequest) GetIdentityId() []byte {
	if x != nil {
		return x.IdentityId
	}
	return nil
}

func (x *TransferRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetDestRegion() string {
	if x != nil {
		return x.DestRegion
	}
	return ""
}

func (x *TransferRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type TransferProof struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SourceChainTipHash []byte                 `protobuf:"bytes,1,opt,name=source_chain_tip_hash,json=sourceChainTipHash,proto3" json:"source_chain_tip_hash,omitempty"`
	SourceSeq          uint64                 `protobuf:"varint,2,opt,name=source_seq,json=sourceSeq,proto3" json:"source_seq,omitempty"`
	TrackerSig         []byte                 `protobuf:"bytes,3,opt,name=tracker_sig,json=trackerSig,proto3" json:"tracker_sig,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransferProof) Reset() {
	*x = TransferProof{}
	mi := &file_proto_rpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferProof) ProtoMessage() {}

func (x *TransferProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferProof.ProtoReflect.Descriptor instead.
func (*TransferProof) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{18}
}

func (x *TransferProof) GetSourceChainTipHash() []byte {
	if x != nil {
		return x.SourceChainTipHash
	}
	return nil
}

func (x *TransferProof) GetSourceSeq() uint64 {
	if x != nil {
		return x.SourceSeq
	}
	return 0
}

func (x *TransferProof) GetTrackerSig() []byte {
	if x != nil {
		return x.TrackerSig
	}
	return nil
}

type StunAllocateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StunAllocateRequest) Reset() {
	*x = StunAllocateRequest{}
	mi := &file_proto_rpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StunAllocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StunAllocateRequest) ProtoMessage() {}

func (x *StunAllocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StunAllocateRequest.ProtoReflect.Descriptor instead.
func (*StunAllocateRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{19}
}

type StunAllocateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalAddr  string                 `protobuf:"bytes,1,opt,name=external_addr,json=externalAddr,proto3" json:"external_addr,omitempty"` // host:port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StunAllocateResponse) Reset() {
	*x = StunAllocateResponse{}
	mi := &file_proto_rpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StunAllocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StunAllocateResponse) ProtoMessage() {}

func (x *StunAllocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StunAllocateResponse.ProtoReflect.Descriptor instead.
func (*StunAllocateResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{20}
}

func (x *StunAllocateResponse) GetExternalAddr() string {
	if x != nil {
		return x.ExternalAddr
	}
	return ""
}

type TurnRelayOpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     []byte                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 16 — uuid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnRelayOpenRequest) Reset() {
	*x = TurnRelayOpenRequest{}
	mi := &file_proto_rpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnRelayOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnRelayOpenRequest) ProtoMessage() {}

func (x *TurnRelayOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnRelayOpenRequest.ProtoReflect.Descriptor instead.
func (*TurnRelayOpenRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{21}
}

func (x *TurnRelayOpenRequest) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

type TurnRelayOpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelayEndpoint string                 `protobuf:"bytes,1,opt,name=relay_endpoint,json=relayEndpoint,proto3" json:"relay_endpoint,omitempty"`
	Token         []byte                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnRelayOpenResponse) Reset() {
	*x = TurnRelayOpenResponse{}
	mi := &file_proto_rpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnRelayOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnRelayOpenResponse) ProtoMessage() {}

func (x *TurnRelayOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnRelayOpenResponse.ProtoReflect.Descriptor instead.
func (*TurnRelayOpenResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{22}
}

func (x *TurnRelayOpenResponse) GetRelayEndpoint() string {
	if x != nil {
		return x.RelayEndpoint
	}
	return ""
}

func (x *TurnRelayOpenResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type BootstrapPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapPeersRequest) Reset() {
	*x = BootstrapPeersRequest{}
	mi := &file_proto_rpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapPeersRequest) ProtoMessage() {}

func (x *BootstrapPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapPeersRequest.ProtoReflect.Descriptor instead.
func (*BootstrapPeersRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{23}
}

type BootstrapPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackerId     []byte                 `protobuf:"bytes,1,opt,name=tracker_id,json=trackerId,proto3" json:"tracker_id,omitempty"`         // 32 bytes — SHA-256 of peer tracker's SPKI
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`                                    // host:port (UDP for QUIC); len ≤ 256, valid UTF-8
	RegionHint    string                 `protobuf:"bytes,3,opt,name=region_hint,json=regionHint,proto3" json:"region_hint,omitempty"`      // human-friendly; len ≤ 64, valid UTF-8
	HealthScore   float64                `protobuf:"fixed64,4,opt,name=health_score,json=healthScore,proto3" json:"health_score,omitempty"` // 0..1; NaN rejected by validator
	LastSeen      uint64                 `protobuf:"varint,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`           // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapPeer) Reset() {
	*x = BootstrapPeer{}
	mi := &file_proto_rpc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapPeer) ProtoMessage() {}

func (x *BootstrapPeer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapPeer.ProtoReflect.Descriptor instead.
func (*BootstrapPeer) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{24}
}

func (x *BootstrapPeer) GetTrackerId() []byte {
	if x != nil {
		return x.TrackerId
	}
	return nil
}

func (x *BootstrapPeer) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *BootstrapPeer) GetRegionHint() string {
	if x != nil {
		return x.RegionHint
	}
	return ""
}

func (x *BootstrapPeer) GetHealthScore() float64 {
	if x != nil {
		return x.HealthScore
	}
	return 0
}

func (x *BootstrapPeer) GetLastSeen() uint64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type BootstrapPeerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuerId      []byte                 `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`     // 32 — issuing tracker's IdentityID
	SignedAt      uint64                 `protobuf:"varint,2,opt,name=signed_at,json=signedAt,proto3" json:"signed_at,omitempty"`    // unix seconds
	ExpiresAt     uint64                 `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // unix seconds
	Peers         []*BootstrapPeer       `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers,omitempty"`
	Sig           []byte                 `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"` // 64 — Ed25519 over CanonicalBootstrapPeerListPreSig(list)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapPeerList) Reset() {
	*x = BootstrapPeerList{}
	mi := &file_proto_rpc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapPeerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapPeerList) ProtoMessage() {}

func (x *BootstrapPeerList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapPeerList.ProtoReflect.Descriptor instead.
func (*BootstrapPeerList) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{25}
}

func (x *BootstrapPeerList) GetIssuerId() []byte {
	if x != nil {
		return x.IssuerId
	}
	return nil
}

func (x *BootstrapPeerList) GetSignedAt() uint64 {
	if x != nil {
		return x.SignedAt
	}
	return 0
}

func (x *BootstrapPeerList) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *BootstrapPeerList) GetPeers() []*BootstrapPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *BootstrapPeerList) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type HeartbeatPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	T             uint64                 `protobuf:"varint,2,opt,name=t,proto3" json:"t,omitempty"` // unix milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_proto_rpc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{26}
}

func (x *HeartbeatPing) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *HeartbeatPing) GetT() uint64 {
	if x != nil {
		return x.T
	}
	return 0
}

type HeartbeatPong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPong) Reset() {
	*x = HeartbeatPong{}
	mi := &file_proto_rpc_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPong) ProtoMessage() {}

func (x *HeartbeatPong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPong.ProtoReflect.Descriptor instead.
func (*HeartbeatPong) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{27}
}

func (x *HeartbeatPong) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type OfferPush struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId      []byte                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`       // 32
	EnvelopeHash    []byte                 `protobuf:"bytes,2,opt,name=envelope_hash,json=envelopeHash,proto3" json:"envelope_hash,omitempty"` // 32
	Model           string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	MaxInputTokens  uint32                 `protobuf:"varint,4,opt,name=max_input_tokens,json=maxInputTokens,proto3" json:"max_input_tokens,omitempty"`
	MaxOutputTokens uint32                 `protobuf:"varint,5,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OfferPush) Reset() {
	*x = OfferPush{}
	mi := &file_proto_rpc_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferPush) ProtoMessage() {}

func (x *OfferPush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferPush.ProtoReflect.Descriptor instead.
func (*OfferPush) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{28}
}

func (x *OfferPush) GetConsumerId() []byte {
	if x != nil {
		return x.ConsumerId
	}
	return nil
}

func (x *OfferPush) GetEnvelopeHash() []byte {
	if x != nil {
		return x.EnvelopeHash
	}
	return nil
}

func (x *OfferPush) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *OfferPush) GetMaxInputTokens() uint32 {
	if x != nil {
		return x.MaxInputTokens
	}
	return 0
}

func (x *OfferPush) GetMaxOutputTokens() uint32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

type OfferDecision struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Accept          bool                   `protobuf:"varint,1,opt,name=accept,proto3" json:"accept,omitempty"`
	EphemeralPubkey []byte                 `protobuf:"bytes,2,opt,name=ephemeral_pubkey,json=ephemeralPubkey,proto3" json:"ephemeral_pubkey,omitempty"` // 32, present iff accept
	RejectReason    string                 `protobuf:"bytes,3,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`          // present iff !accept
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OfferDecision) Reset() {
	*x = OfferDecision{}
	mi := &file_proto_rpc_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferDecision) ProtoMessage() {}

func (x *OfferDecision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferDecision.ProtoReflect.Descriptor instead.
func (*OfferDecision) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{29}
}

func (x *OfferDecision) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

func (x *OfferDecision) GetEphemeralPubkey() []byte {
	if x != nil {
		return x.EphemeralPubkey
	}
	return nil
}

func (x *OfferDecision) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type SettlementPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreimageHash  []byte                 `protobuf:"bytes,1,opt,name=preimage_hash,json=preimageHash,proto3" json:"preimage_hash,omitempty"` // 32
	PreimageBody  []byte                 `protobuf:"bytes,2,opt,name=preimage_body,json=preimageBody,proto3" json:"preimage_body,omitempty"` // serialized EntryBody
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementPush) Reset() {
	*x = SettlementPush{}
	mi := &file_proto_rpc_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementPush) ProtoMessage() {}

func (x *SettlementPush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementPush.ProtoReflect.Descriptor instead.
func (*SettlementPush) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{30}
}

func (x *SettlementPush) GetPreimageHash() []byte {
	if x != nil {
		return x.PreimageHash
	}
	return nil
}

func (x *SettlementPush) GetPreimageBody() []byte {
	if x != nil {
		return x.PreimageBody
	}
	return nil
}

var File_proto_rpc_proto protoreflect.FileDescriptor

const file_proto_rpc_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/rpc.proto\x12\x11tokenbay.proto.v1\"8\n" +
	"\bRpcError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\\\n" +
	"\n" +
	"RpcRequest\x124\n" +
	"\x06method\x18\x01 \x01(\x0e2\x1c.tokenbay.proto.v1.RpcMethodR\x06method\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x90\x01\n" +
	"\vRpcResponse\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.tokenbay.proto.v1.RpcStatusR\x06status\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x121\n" +
	"\x05error\x18\x03 \x01(\v2\x1b.tokenbay.proto.v1.RpcErrorR\x05error\"\xb6\x01\n" +
	"\rEnrollRequest\x12'\n" +
	"\x0fidentity_pubkey\x18\x01 \x01(\fR\x0eidentityPubkey\x12\x12\n" +
	"\x04role\x18\x02 \x01(\rR\x04role\x12/\n" +
	"\x13account_fingerprint\x18\x03 \x01(\fR\x12accountFingerprint\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\x12!\n" +
	"\fconsumer_sig\x18\x05 \x01(\fR\vconsumerSig\"\x95\x01\n" +
	"\x0eEnrollResponse\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\fR\n" +
	"identityId\x122\n" +
	"\x15starter_grant_credits\x18\x02 \x01(\x04R\x13starterGrantCredits\x12.\n" +
	"\x13starter_grant_entry\x18\x03 \x01(\fR\x11starterGrantEntry\"\x85\x01\n" +
	"\x10SeederAssignment\x12\x1f\n" +
	"\vseeder_addr\x18\x01 \x01(\fR\n" +
	"seederAddr\x12#\n" +
	"\rseeder_pubkey\x18\x02 \x01(\fR\fseederPubkey\x12+\n" +
	"\x11reservation_token\x18\x03 \x01(\fR\x10reservationToken\"$\n" +
	"\n" +
	"NoCapacity\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xa4\x01\n" +
	"\x06Queued\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\fR\trequestId\x12D\n" +
	"\rposition_band\x18\x02 \x01(\x0e2\x1f.tokenbay.proto.v1.PositionBandR\fpositionBand\x125\n" +
	"\beta_band\x18\x03 \x01(\x0e2\x1a.tokenbay.proto.v1.EtaBandR\aetaBand\"g\n" +
	"\bRejected\x127\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x1f.tokenbay.proto.v1.RejectReasonR\x06reason\x12\"\n" +
	"\rretry_after_s\x18\x02 \x01(\rR\vretryAfterS\"\xa8\x02\n" +
	"\x15BrokerRequestResponse\x12R\n" +
	"\x11seeder_assignment\x18\x01 \x01(\v2#.tokenbay.proto.v1.SeederAssignmentH\x00R\x10seederAssignment\x12@\n" +
	"\vno_capacity\x18\x02 \x01(\v2\x1d.tokenbay.proto.v1.NoCapacityH\x00R\n" +
	"noCapacity\x123\n" +
	"\x06queued\x18\x03 \x01(\v2\x19.tokenbay.proto.v1.QueuedH\x00R\x06queued\x129\n" +
	"\brejected\x18\x04 \x01(\v2\x1b.tokenbay.proto.v1.RejectedH\x00R\brejectedB\t\n" +
	"\aoutcome\"1\n" +
	"\x0eBalanceRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\fR\n" +
	"identityId\"W\n" +
	"\rSettleRequest\x12#\n" +
	"\rpreimage_hash\x18\x01 \x01(\fR\fpreimageHash\x12!\n" +
	"\fconsumer_sig\x18\x02 \x01(\fR\vconsumerSig\"\v\n" +
	"\tSettleAck\"\xa9\x01\n" +
	"\vUsageReport\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\fR\trequestId\x12!\n" +
	"\finput_tokens\x18\x02 \x01(\rR\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x03 \x01(\rR\foutputTokens\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"seeder_sig\x18\x05 \x01(\fR\tseederSig\"\n" +
	"\n" +
	"\bUsageAck\"\x98\x01\n" +
	"\rAdvertisement\x12\x16\n" +
	"\x06models\x18\x01 \x03(\tR\x06models\x12\x1f\n" +
	"\vmax_context\x18\x02 \x01(\rR\n" +
	"maxContext\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable\x12\x1a\n" +
	"\bheadroom\x18\x04 \x01(\x02R\bheadroom\x12\x14\n" +
	"\x05tiers\x18\x05 \x01(\rR\x05tiers\"\x0e\n" +
	"\fAdvertiseAck\"\x81\x01\n" +
	"\x0fTransferRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\fR\n" +
	"identityId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x1f\n" +
	"\vdest_region\x18\x03 \x01(\tR\n" +
	"destRegion\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\"\x82\x01\n" +
	"\rTransferProof\x121\n" +
	"\x15source_chain_tip_hash\x18\x01 \x01(\fR\x12sourceChainTipHash\x12\x1d\n" +
	"\n" +
	"source_seq\x18\x02 \x01(\x04R\tsourceSeq\x12\x1f\n" +
	"\vtracker_sig\x18\x03 \x01(\fR\n" +
	"trackerSig\"\x15\n" +
	"\x13StunAllocateRequest\";\n" +
	"\x14StunAllocateResponse\x12#\n" +
	"\rexternal_addr\x18\x01 \x01(\tR\fexternalAddr\"5\n" +
	"\x14TurnRelayOpenRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\fR\tsessionId\"T\n" +
	"\x15TurnRelayOpenResponse\x12%\n" +
	"\x0erelay_endpoint\x18\x01 \x01(\tR\rrelayEndpoint\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05token\"\x17\n" +
	"\x15BootstrapPeersRequest\"\xa3\x01\n" +
	"\rBootstrapPeer\x12\x1d\n" +
	"\n" +
	"tracker_id\x18\x01 \x01(\fR\ttrackerId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1f\n" +
	"\vregion_hint\x18\x03 \x01(\tR\n" +
	"regionHint\x12!\n" +
	"\fhealth_score\x18\x04 \x01(\x01R\vhealthScore\x12\x1b\n" +
	"\tlast_seen\x18\x05 \x01(\x04R\blastSeen\"\xb6\x01\n" +
	"\x11BootstrapPeerList\x12\x1b\n" +
	"\tissuer_id\x18\x01 \x01(\fR\bissuerId\x12\x1b\n" +
	"\tsigned_at\x18\x02 \x01(\x04R\bsignedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x04R\texpiresAt\x126\n" +
	"\x05peers\x18\x04 \x03(\v2 .tokenbay.proto.v1.BootstrapPeerR\x05peers\x12\x10\n" +
	"\x03sig\x18\x05 \x01(\fR\x03sig\"/\n" +
	"\rHeartbeatPing\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\f\n" +
	"\x01t\x18\x02 \x01(\x04R\x01t\"!\n" +
	"\rHeartbeatPong\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\"\xbd\x01\n" +
	"\tOfferPush\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\fR\n" +
	"consumerId\x12#\n" +
	"\renvelope_hash\x18\x02 \x01(\fR\fenvelopeHash\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12(\n" +
	"\x10max_input_tokens\x18\x04 \x01(\rR\x0emaxInputTokens\x12*\n" +
	"\x11max_output_tokens\x18\x05 \x01(\rR\x0fmaxOutputTokens\"w\n" +
	"\rOfferDecision\x12\x16\n" +
	"\x06accept\x18\x01 \x01(\bR\x06accept\x12)\n" +
	"\x10ephemeral_pubkey\x18\x02 \x01(\fR\x0fephemeralPubkey\x12#\n" +
	"\rreject_reason\x18\x03 \x01(\tR\frejectReason\"Z\n" +
	"\x0eSettlementPush\x12#\n" +
	"\rpreimage_hash\x18\x01 \x01(\fR\fpreimageHash\x12#\n" +
	"\rpreimage_body\x18\x02 \x01(\fR\fpreimageBody*\xc2\x02\n" +
	"\tRpcMethod\x12\x1a\n" +
	"\x16RPC_METHOD_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RPC_METHOD_ENROLL\x10\x01\x12\x1d\n" +
	"\x19RPC_METHOD_BROKER_REQUEST\x10\x02\x12\x16\n" +
	"\x12RPC_METHOD_BALANCE\x10\x03\x12\x15\n" +
	"\x11RPC_METHOD_SETTLE\x10\x04\x12\x1b\n" +
	"\x17RPC_METHOD_USAGE_REPORT\x10\x05\x12\x18\n" +
	"\x14RPC_METHOD_ADVERTISE\x10\x06\x12\x1f\n" +
	"\x1bRPC_METHOD_TRANSFER_REQUEST\x10\a\x12\x1c\n" +
	"\x18RPC_METHOD_STUN_ALLOCATE\x10\b\x12\x1e\n" +
	"\x1aRPC_METHOD_TURN_RELAY_OPEN\x10\t\x12\x1e\n" +
	"\x1aRPC_METHOD_BOOTSTRAP_PEERS\x10\n" +
	"*\xd8\x01\n" +
	"\tRpcStatus\x12\x1a\n" +
	"\x16RPC_STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rRPC_STATUS_OK\x10\x01\x12\x16\n" +
	"\x12RPC_STATUS_INVALID\x10\x02\x12\x1a\n" +
	"\x16RPC_STATUS_NO_CAPACITY\x10\x03\x12\x15\n" +
	"\x11RPC_STATUS_FROZEN\x10\x04\x12\x17\n" +
	"\x13RPC_STATUS_INTERNAL\x10\x05\x12\x1e\n" +
	"\x1aRPC_STATUS_UNAUTHENTICATED\x10\x06\x12\x18\n" +
	"\x14RPC_STATUS_NOT_FOUND\x10\a*\x9d\x01\n" +
	"\fPositionBand\x12\x1d\n" +
	"\x19POSITION_BAND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15POSITION_BAND_1_TO_10\x10\x01\x12\x1a\n" +
	"\x16POSITION_BAND_11_TO_50\x10\x02\x12\x1b\n" +
	"\x17POSITION_BAND_51_TO_200\x10\x03\x12\x1a\n" +
	"\x16POSITION_BAND_200_PLUS\x10\x04*}\n" +
	"\aEtaBand\x12\x18\n" +
	"\x14ETA_BAND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fETA_BAND_LT_30S\x10\x01\x12\x16\n" +
	"\x12ETA_BAND_30S_TO_2M\x10\x02\x12\x15\n" +
	"\x11ETA_BAND_2M_TO_5M\x10\x03\x12\x14\n" +
	"\x10ETA_BAND_5M_PLUS\x10\x04*s\n" +
	"\fRejectReason\x12\x1d\n" +
	"\x19REJECT_REASON_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fREJECT_REASON_REGION_OVERLOADED\x10\x01\x12\x1f\n" +
	"\x1bREJECT_REASON_QUEUE_TIMEOUT\x10\x02B-Z+github.com/token-bay/token-bay/shared/protob\x06proto3"

var (
	file_proto_rpc_proto_rawDescOnce sync.Once
	file_proto_rpc_proto_rawDescData []byte
)

func file_proto_rpc_proto_rawDescGZIP() []byte {
	file_proto_rpc_proto_rawDescOnce.Do(func() {
		file_proto_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rpc_proto_rawDesc), len(file_proto_rpc_proto_rawDesc)))
	})
	return file_proto_rpc_proto_rawDescData
}

var (
	file_proto_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
	file_proto_rpc_proto_msgTypes  = make([]protoimpl.MessageInfo, 31)
	file_proto_rpc_proto_goTypes   = []any{
		(RpcMethod)(0),                // 0: tokenbay.proto.v1.RpcMethod
		(RpcStatus)(0),                // 1: tokenbay.proto.v1.RpcStatus
		(PositionBand)(0),             // 2: tokenbay.proto.v1.PositionBand
		(EtaBand)(0),                  // 3: tokenbay.proto.v1.EtaBand
		(RejectReason)(0),             // 4: tokenbay.proto.v1.RejectReason
		(*RpcError)(nil),              // 5: tokenbay.proto.v1.RpcError
		(*RpcRequest)(nil),            // 6: tokenbay.proto.v1.RpcRequest
		(*RpcResponse)(nil),           // 7: tokenbay.proto.v1.RpcResponse
		(*EnrollRequest)(nil),         // 8: tokenbay.proto.v1.EnrollRequest
		(*EnrollResponse)(nil),        // 9: tokenbay.proto.v1.EnrollResponse
		(*SeederAssignment)(nil),      // 10: tokenbay.proto.v1.SeederAssignment
		(*NoCapacity)(nil),            // 11: tokenbay.proto.v1.NoCapacity
		(*Queued)(nil),                // 12: tokenbay.proto.v1.Queued
		(*Rejected)(nil),              // 13: tokenbay.proto.v1.Rejected
		(*BrokerRequestResponse)(nil), // 14: tokenbay.proto.v1.BrokerRequestResponse
		(*BalanceRequest)(nil),        // 15: tokenbay.proto.v1.BalanceRequest
		(*SettleRequest)(nil),         // 16: tokenbay.proto.v1.SettleRequest
		(*SettleAck)(nil),             // 17: tokenbay.proto.v1.SettleAck
		(*UsageReport)(nil),           // 18: tokenbay.proto.v1.UsageReport
		(*UsageAck)(nil),              // 19: tokenbay.proto.v1.UsageAck
		(*Advertisement)(nil),         // 20: tokenbay.proto.v1.Advertisement
		(*AdvertiseAck)(nil),          // 21: tokenbay.proto.v1.AdvertiseAck
		(*TransferRequest)(nil),       // 22: tokenbay.proto.v1.TransferRequest
		(*TransferProof)(nil),         // 23: tokenbay.proto.v1.TransferProof
		(*StunAllocateRequest)(nil),   // 24: tokenbay.proto.v1.StunAllocateRequest
		(*StunAllocateResponse)(nil),  // 25: tokenbay.proto.v1.StunAllocateResponse
		(*TurnRelayOpenRequest)(nil),  // 26: tokenbay.proto.v1.TurnRelayOpenRequest
		(*TurnRelayOpenResponse)(nil), // 27: tokenbay.proto.v1.TurnRelayOpenResponse
		(*BootstrapPeersRequest)(nil), // 28: tokenbay.proto.v1.BootstrapPeersRequest
		(*BootstrapPeer)(nil),         // 29: tokenbay.proto.v1.BootstrapPeer
		(*BootstrapPeerList)(nil),     // 30: tokenbay.proto.v1.BootstrapPeerList
		(*HeartbeatPing)(nil),         // 31: tokenbay.proto.v1.HeartbeatPing
		(*HeartbeatPong)(nil),         // 32: tokenbay.proto.v1.HeartbeatPong
		(*OfferPush)(nil),             // 33: tokenbay.proto.v1.OfferPush
		(*OfferDecision)(nil),         // 34: tokenbay.proto.v1.OfferDecision
		(*SettlementPush)(nil),        // 35: tokenbay.proto.v1.SettlementPush
	}
)
var file_proto_rpc_proto_depIdxs = []int32{
	0,  // 0: tokenbay.proto.v1.RpcRequest.method:type_name -> tokenbay.proto.v1.RpcMethod
	1,  // 1: tokenbay.proto.v1.RpcResponse.status:type_name -> tokenbay.proto.v1.RpcStatus
	5,  // 2: tokenbay.proto.v1.RpcResponse.error:type_name -> tokenbay.proto.v1.RpcError
	2,  // 3: tokenbay.proto.v1.Queued.position_band:type_name -> tokenbay.proto.v1.PositionBand
	3,  // 4: tokenbay.proto.v1.Queued.eta_band:type_name -> tokenbay.proto.v1.EtaBand
	4,  // 5: tokenbay.proto.v1.Rejected.reason:type_name -> tokenbay.proto.v1.RejectReason
	10, // 6: tokenbay.proto.v1.BrokerRequestResponse.seeder_assignment:type_name -> tokenbay.proto.v1.SeederAssignment
	11, // 7: tokenbay.proto.v1.BrokerRequestResponse.no_capacity:type_name -> tokenbay.proto.v1.NoCapacity
	12, // 8: tokenbay.proto.v1.BrokerRequestResponse.queued:type_name -> tokenbay.proto.v1.Queued
	13, // 9: tokenbay.proto.v1.BrokerRequestResponse.rejected:type_name -> tokenbay.proto.v1.Rejected
	29, // 10: tokenbay.proto.v1.BootstrapPeerList.peers:type_name -> tokenbay.proto.v1.BootstrapPeer
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_rpc_proto_init() }
func file_proto_rpc_proto_init() {
	if File_proto_rpc_proto != nil {
		return
	}
	file_proto_rpc_proto_msgTypes[9].OneofWrappers = []any{
		(*BrokerRequestResponse_SeederAssignment)(nil),
		(*BrokerRequestResponse_NoCapacity)(nil),
		(*BrokerRequestResponse_Queued)(nil),
		(*BrokerRequestResponse_Rejected)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rpc_proto_rawDesc), len(file_proto_rpc_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_rpc_proto_goTypes,
		DependencyIndexes: file_proto_rpc_proto_depIdxs,
		EnumInfos:         file_proto_rpc_proto_enumTypes,
		MessageInfos:      file_proto_rpc_proto_msgTypes,
	}.Build()
	File_proto_rpc_proto = out.File
	file_proto_rpc_proto_goTypes = nil
	file_proto_rpc_proto_depIdxs = nil
}
