// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/rpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RpcMethod identifies the unary RPC the client is invoking.
//
// Method 0 (RPC_METHOD_UNSPECIFIED) is reserved as the heartbeat-channel
// marker on the dedicated heartbeat stream — it is NOT an "unset" sentinel.
// Validators reject method 0 on regular RPC streams.
type RpcMethod int32

const (
	RpcMethod_RPC_METHOD_UNSPECIFIED      RpcMethod = 0 // heartbeat-channel marker
	RpcMethod_RPC_METHOD_ENROLL           RpcMethod = 1
	RpcMethod_RPC_METHOD_BROKER_REQUEST   RpcMethod = 2
	RpcMethod_RPC_METHOD_BALANCE          RpcMethod = 3
	RpcMethod_RPC_METHOD_SETTLE           RpcMethod = 4
	RpcMethod_RPC_METHOD_USAGE_REPORT     RpcMethod = 5
	RpcMethod_RPC_METHOD_ADVERTISE        RpcMethod = 6
	RpcMethod_RPC_METHOD_TRANSFER_REQUEST RpcMethod = 7
	RpcMethod_RPC_METHOD_STUN_ALLOCATE    RpcMethod = 8
	RpcMethod_RPC_METHOD_TURN_RELAY_OPEN  RpcMethod = 9
)

// Enum value maps for RpcMethod.
var (
	RpcMethod_name = map[int32]string{
		0: "RPC_METHOD_UNSPECIFIED",
		1: "RPC_METHOD_ENROLL",
		2: "RPC_METHOD_BROKER_REQUEST",
		3: "RPC_METHOD_BALANCE",
		4: "RPC_METHOD_SETTLE",
		5: "RPC_METHOD_USAGE_REPORT",
		6: "RPC_METHOD_ADVERTISE",
		7: "RPC_METHOD_TRANSFER_REQUEST",
		8: "RPC_METHOD_STUN_ALLOCATE",
		9: "RPC_METHOD_TURN_RELAY_OPEN",
	}
	RpcMethod_value = map[string]int32{
		"RPC_METHOD_UNSPECIFIED":      0,
		"RPC_METHOD_ENROLL":           1,
		"RPC_METHOD_BROKER_REQUEST":   2,
		"RPC_METHOD_BALANCE":          3,
		"RPC_METHOD_SETTLE":           4,
		"RPC_METHOD_USAGE_REPORT":     5,
		"RPC_METHOD_ADVERTISE":        6,
		"RPC_METHOD_TRANSFER_REQUEST": 7,
		"RPC_METHOD_STUN_ALLOCATE":    8,
		"RPC_METHOD_TURN_RELAY_OPEN":  9,
	}
)

func (x RpcMethod) Enum() *RpcMethod {
	p := new(RpcMethod)
	*p = x
	return p
}

func (x RpcMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rpc_proto_enumTypes[0].Descriptor()
}

func (RpcMethod) Type() protoreflect.EnumType {
	return &file_proto_rpc_proto_enumTypes[0]
}

func (x RpcMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcMethod.Descriptor instead.
func (RpcMethod) EnumDescriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{0}
}

type RpcStatus int32

const (
	RpcStatus_RPC_STATUS_UNSPECIFIED     RpcStatus = 0
	RpcStatus_RPC_STATUS_OK              RpcStatus = 1
	RpcStatus_RPC_STATUS_INVALID         RpcStatus = 2
	RpcStatus_RPC_STATUS_NO_CAPACITY     RpcStatus = 3
	RpcStatus_RPC_STATUS_FROZEN          RpcStatus = 4
	RpcStatus_RPC_STATUS_INTERNAL        RpcStatus = 5
	RpcStatus_RPC_STATUS_UNAUTHENTICATED RpcStatus = 6
	RpcStatus_RPC_STATUS_NOT_FOUND       RpcStatus = 7
)

// Enum value maps for RpcStatus.
var (
	RpcStatus_name = map[int32]string{
		0: "RPC_STATUS_UNSPECIFIED",
		1: "RPC_STATUS_OK",
		2: "RPC_STATUS_INVALID",
		3: "RPC_STATUS_NO_CAPACITY",
		4: "RPC_STATUS_FROZEN",
		5: "RPC_STATUS_INTERNAL",
		6: "RPC_STATUS_UNAUTHENTICATED",
		7: "RPC_STATUS_NOT_FOUND",
	}
	RpcStatus_value = map[string]int32{
		"RPC_STATUS_UNSPECIFIED":     0,
		"RPC_STATUS_OK":              1,
		"RPC_STATUS_INVALID":         2,
		"RPC_STATUS_NO_CAPACITY":     3,
		"RPC_STATUS_FROZEN":          4,
		"RPC_STATUS_INTERNAL":        5,
		"RPC_STATUS_UNAUTHENTICATED": 6,
		"RPC_STATUS_NOT_FOUND":       7,
	}
)

func (x RpcStatus) Enum() *RpcStatus {
	p := new(RpcStatus)
	*p = x
	return p
}

func (x RpcStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rpc_proto_enumTypes[1].Descriptor()
}

func (RpcStatus) Type() protoreflect.EnumType {
	return &file_proto_rpc_proto_enumTypes[1]
}

func (x RpcStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcStatus.Descriptor instead.
func (RpcStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{1}
}

type RpcError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcError) Reset() {
	*x = RpcError{}
	mi := &file_proto_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcError) ProtoMessage() {}

func (x *RpcError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcError.ProtoReflect.Descriptor instead.
func (*RpcError) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RpcError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RpcError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        RpcMethod              `protobuf:"varint,1,opt,name=method,proto3,enum=tokenbay.proto.v1.RpcMethod" json:"method,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	mi := &file_proto_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RpcRequest) GetMethod() RpcMethod {
	if x != nil {
		return x.Method
	}
	return RpcMethod_RPC_METHOD_UNSPECIFIED
}

func (x *RpcRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        RpcStatus              `protobuf:"varint,1,opt,name=status,proto3,enum=tokenbay.proto.v1.RpcStatus" json:"status,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Error         *RpcError              `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	mi := &file_proto_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RpcResponse) GetStatus() RpcStatus {
	if x != nil {
		return x.Status
	}
	return RpcStatus_RPC_STATUS_UNSPECIFIED
}

func (x *RpcResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RpcResponse) GetError() *RpcError {
	if x != nil {
		return x.Error
	}
	return nil
}

type EnrollRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IdentityPubkey     []byte                 `protobuf:"bytes,1,opt,name=identity_pubkey,json=identityPubkey,proto3" json:"identity_pubkey,omitempty"`             // 32
	Role               uint32                 `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`                                                      // bit0: consumer, bit1: seeder
	AccountFingerprint []byte                 `protobuf:"bytes,3,opt,name=account_fingerprint,json=accountFingerprint,proto3" json:"account_fingerprint,omitempty"` // 32 — SHA-256(orgId)
	Nonce              []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`                                                     // 16
	ConsumerSig        []byte                 `protobuf:"bytes,5,opt,name=consumer_sig,json=consumerSig,proto3" json:"consumer_sig,omitempty"`                      // 64
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_proto_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *EnrollRequest) GetIdentityPubkey() []byte {
	if x != nil {
		return x.IdentityPubkey
	}
	return nil
}

func (x *EnrollRequest) GetRole() uint32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *EnrollRequest) GetAccountFingerprint() []byte {
	if x != nil {
		return x.AccountFingerprint
	}
	return nil
}

func (x *EnrollRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EnrollRequest) GetConsumerSig() []byte {
	if x != nil {
		return x.ConsumerSig
	}
	return nil
}

type EnrollResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IdentityId          []byte                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"` // 32
	StarterGrantCredits uint64                 `protobuf:"varint,2,opt,name=starter_grant_credits,json=starterGrantCredits,proto3" json:"starter_grant_credits,omitempty"`
	StarterGrantEntry   []byte                 `protobuf:"bytes,3,opt,name=starter_grant_entry,json=starterGrantEntry,proto3" json:"starter_grant_entry,omitempty"` // serialized EntrySigned
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_proto_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *EnrollResponse) GetIdentityId() []byte {
	if x != nil {
		return x.IdentityId
	}
	return nil
}

func (x *EnrollResponse) GetStarterGrantCredits() uint64 {
	if x != nil {
		return x.StarterGrantCredits
	}
	return 0
}

func (x *EnrollResponse) GetStarterGrantEntry() []byte {
	if x != nil {
		return x.StarterGrantEntry
	}
	return nil
}

type BrokerResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SeederAddr       []byte                 `protobuf:"bytes,1,opt,name=seeder_addr,json=seederAddr,proto3" json:"seeder_addr,omitempty"`       // utf-8 host:port
	SeederPubkey     []byte                 `protobuf:"bytes,2,opt,name=seeder_pubkey,json=seederPubkey,proto3" json:"seeder_pubkey,omitempty"` // 32
	ReservationToken []byte                 `protobuf:"bytes,3,opt,name=reservation_token,json=reservationToken,proto3" json:"reservation_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BrokerResponse) Reset() {
	*x = BrokerResponse{}
	mi := &file_proto_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokerResponse) ProtoMessage() {}

func (x *BrokerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokerResponse.ProtoReflect.Descriptor instead.
func (*BrokerResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *BrokerResponse) GetSeederAddr() []byte {
	if x != nil {
		return x.SeederAddr
	}
	return nil
}

func (x *BrokerResponse) GetSeederPubkey() []byte {
	if x != nil {
		return x.SeederPubkey
	}
	return nil
}

func (x *BrokerResponse) GetReservationToken() []byte {
	if x != nil {
		return x.ReservationToken
	}
	return nil
}

type NoCapacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoCapacity) Reset() {
	*x = NoCapacity{}
	mi := &file_proto_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoCapacity) ProtoMessage() {}

func (x *NoCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoCapacity.ProtoReflect.Descriptor instead.
func (*NoCapacity) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *NoCapacity) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    []byte                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"` // 32
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_proto_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *BalanceRequest) GetIdentityId() []byte {
	if x != nil {
		return x.IdentityId
	}
	return nil
}

type SettleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreimageHash  []byte                 `protobuf:"bytes,1,opt,name=preimage_hash,json=preimageHash,proto3" json:"preimage_hash,omitempty"` // 32
	ConsumerSig   []byte                 `protobuf:"bytes,2,opt,name=consumer_sig,json=consumerSig,proto3" json:"consumer_sig,omitempty"`    // 64
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleRequest) Reset() {
	*x = SettleRequest{}
	mi := &file_proto_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleRequest) ProtoMessage() {}

func (x *SettleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleRequest.ProtoReflect.Descriptor instead.
func (*SettleRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *SettleRequest) GetPreimageHash() []byte {
	if x != nil {
		return x.PreimageHash
	}
	return nil
}

func (x *SettleRequest) GetConsumerSig() []byte {
	if x != nil {
		return x.ConsumerSig
	}
	return nil
}

type SettleAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleAck) Reset() {
	*x = SettleAck{}
	mi := &file_proto_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleAck) ProtoMessage() {}

func (x *SettleAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleAck.ProtoReflect.Descriptor instead.
func (*SettleAck) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{9}
}

type UsageReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     []byte                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 16 — uuid
	InputTokens   uint32                 `protobuf:"varint,2,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  uint32                 `protobuf:"varint,3,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	SeederSig     []byte                 `protobuf:"bytes,5,opt,name=seeder_sig,json=seederSig,proto3" json:"seeder_sig,omitempty"` // 64
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageReport) Reset() {
	*x = UsageReport{}
	mi := &file_proto_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageReport) ProtoMessage() {}

func (x *UsageReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageReport.ProtoReflect.Descriptor instead.
func (*UsageReport) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *UsageReport) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *UsageReport) GetInputTokens() uint32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *UsageReport) GetOutputTokens() uint32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *UsageReport) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UsageReport) GetSeederSig() []byte {
	if x != nil {
		return x.SeederSig
	}
	return nil
}

type UsageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageAck) Reset() {
	*x = UsageAck{}
	mi := &file_proto_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageAck) ProtoMessage() {}

func (x *UsageAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageAck.ProtoReflect.Descriptor instead.
func (*UsageAck) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{11}
}

type Advertisement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []string               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	MaxContext    uint32                 `protobuf:"varint,2,opt,name=max_context,json=maxContext,proto3" json:"max_context,omitempty"`
	Available     bool                   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	Headroom      float32                `protobuf:"fixed32,4,opt,name=headroom,proto3" json:"headroom,omitempty"`
	Tiers         uint32                 `protobuf:"varint,5,opt,name=tiers,proto3" json:"tiers,omitempty"` // bitmask: bit0 standard, bit1 tee
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Advertisement) Reset() {
	*x = Advertisement{}
	mi := &file_proto_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Advertisement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Advertisement) ProtoMessage() {}

func (x *Advertisement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Advertisement.ProtoReflect.Descriptor instead.
func (*Advertisement) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *Advertisement) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *Advertisement) GetMaxContext() uint32 {
	if x != nil {
		return x.MaxContext
	}
	return 0
}

func (x *Advertisement) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *Advertisement) GetHeadroom() float32 {
	if x != nil {
		return x.Headroom
	}
	return 0
}

func (x *Advertisement) GetTiers() uint32 {
	if x != nil {
		return x.Tiers
	}
	return 0
}

type AdvertiseAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvertiseAck) Reset() {
	*x = AdvertiseAck{}
	mi := &file_proto_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvertiseAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvertiseAck) ProtoMessage() {}

func (x *AdvertiseAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvertiseAck.ProtoReflect.Descriptor instead.
func (*AdvertiseAck) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{13}
}

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    []byte                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	DestRegion    string                 `protobuf:"bytes,3,opt,name=dest_region,json=destRegion,proto3" json:"dest_region,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_proto_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *TransferRequest) GetIdentityId() []byte {
	if x != nil {
		return x.IdentityId
	}
	return nil
}

func (x *TransferRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetDestRegion() string {
	if x != nil {
		return x.DestRegion
	}
	return ""
}

func (x *TransferRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type TransferProof struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SourceChainTipHash []byte                 `protobuf:"bytes,1,opt,name=source_chain_tip_hash,json=sourceChainTipHash,proto3" json:"source_chain_tip_hash,omitempty"`
	SourceSeq          uint64                 `protobuf:"varint,2,opt,name=source_seq,json=sourceSeq,proto3" json:"source_seq,omitempty"`
	TrackerSig         []byte                 `protobuf:"bytes,3,opt,name=tracker_sig,json=trackerSig,proto3" json:"tracker_sig,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransferProof) Reset() {
	*x = TransferProof{}
	mi := &file_proto_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferProof) ProtoMessage() {}

func (x *TransferProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferProof.ProtoReflect.Descriptor instead.
func (*TransferProof) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *TransferProof) GetSourceChainTipHash() []byte {
	if x != nil {
		return x.SourceChainTipHash
	}
	return nil
}

func (x *TransferProof) GetSourceSeq() uint64 {
	if x != nil {
		return x.SourceSeq
	}
	return 0
}

func (x *TransferProof) GetTrackerSig() []byte {
	if x != nil {
		return x.TrackerSig
	}
	return nil
}

type StunAllocateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StunAllocateRequest) Reset() {
	*x = StunAllocateRequest{}
	mi := &file_proto_rpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StunAllocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StunAllocateRequest) ProtoMessage() {}

func (x *StunAllocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StunAllocateRequest.ProtoReflect.Descriptor instead.
func (*StunAllocateRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{16}
}

type StunAllocateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalAddr  string                 `protobuf:"bytes,1,opt,name=external_addr,json=externalAddr,proto3" json:"external_addr,omitempty"` // host:port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StunAllocateResponse) Reset() {
	*x = StunAllocateResponse{}
	mi := &file_proto_rpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StunAllocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StunAllocateResponse) ProtoMessage() {}

func (x *StunAllocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StunAllocateResponse.ProtoReflect.Descriptor instead.
func (*StunAllocateResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{17}
}

func (x *StunAllocateResponse) GetExternalAddr() string {
	if x != nil {
		return x.ExternalAddr
	}
	return ""
}

type TurnRelayOpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     []byte                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 16 — uuid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnRelayOpenRequest) Reset() {
	*x = TurnRelayOpenRequest{}
	mi := &file_proto_rpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnRelayOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnRelayOpenRequest) ProtoMessage() {}

func (x *TurnRelayOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnRelayOpenRequest.ProtoReflect.Descriptor instead.
func (*TurnRelayOpenRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{18}
}

func (x *TurnRelayOpenRequest) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

type TurnRelayOpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelayEndpoint string                 `protobuf:"bytes,1,opt,name=relay_endpoint,json=relayEndpoint,proto3" json:"relay_endpoint,omitempty"`
	Token         []byte                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnRelayOpenResponse) Reset() {
	*x = TurnRelayOpenResponse{}
	mi := &file_proto_rpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnRelayOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnRelayOpenResponse) ProtoMessage() {}

func (x *TurnRelayOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnRelayOpenResponse.ProtoReflect.Descriptor instead.
func (*TurnRelayOpenResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{19}
}

func (x *TurnRelayOpenResponse) GetRelayEndpoint() string {
	if x != nil {
		return x.RelayEndpoint
	}
	return ""
}

func (x *TurnRelayOpenResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type HeartbeatPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	T             uint64                 `protobuf:"varint,2,opt,name=t,proto3" json:"t,omitempty"` // unix milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPing) Reset() {
	*x = HeartbeatPing{}
	mi := &file_proto_rpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPing) ProtoMessage() {}

func (x *HeartbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPing.ProtoReflect.Descriptor instead.
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{20}
}

func (x *HeartbeatPing) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *HeartbeatPing) GetT() uint64 {
	if x != nil {
		return x.T
	}
	return 0
}

type HeartbeatPong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPong) Reset() {
	*x = HeartbeatPong{}
	mi := &file_proto_rpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPong) ProtoMessage() {}

func (x *HeartbeatPong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPong.ProtoReflect.Descriptor instead.
func (*HeartbeatPong) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{21}
}

func (x *HeartbeatPong) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type OfferPush struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId      []byte                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`       // 32
	EnvelopeHash    []byte                 `protobuf:"bytes,2,opt,name=envelope_hash,json=envelopeHash,proto3" json:"envelope_hash,omitempty"` // 32
	Model           string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	MaxInputTokens  uint32                 `protobuf:"varint,4,opt,name=max_input_tokens,json=maxInputTokens,proto3" json:"max_input_tokens,omitempty"`
	MaxOutputTokens uint32                 `protobuf:"varint,5,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OfferPush) Reset() {
	*x = OfferPush{}
	mi := &file_proto_rpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferPush) ProtoMessage() {}

func (x *OfferPush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferPush.ProtoReflect.Descriptor instead.
func (*OfferPush) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{22}
}

func (x *OfferPush) GetConsumerId() []byte {
	if x != nil {
		return x.ConsumerId
	}
	return nil
}

func (x *OfferPush) GetEnvelopeHash() []byte {
	if x != nil {
		return x.EnvelopeHash
	}
	return nil
}

func (x *OfferPush) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *OfferPush) GetMaxInputTokens() uint32 {
	if x != nil {
		return x.MaxInputTokens
	}
	return 0
}

func (x *OfferPush) GetMaxOutputTokens() uint32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

type OfferDecision struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Accept          bool                   `protobuf:"varint,1,opt,name=accept,proto3" json:"accept,omitempty"`
	EphemeralPubkey []byte                 `protobuf:"bytes,2,opt,name=ephemeral_pubkey,json=ephemeralPubkey,proto3" json:"ephemeral_pubkey,omitempty"` // 32, present iff accept
	RejectReason    string                 `protobuf:"bytes,3,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`          // present iff !accept
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OfferDecision) Reset() {
	*x = OfferDecision{}
	mi := &file_proto_rpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferDecision) ProtoMessage() {}

func (x *OfferDecision) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferDecision.ProtoReflect.Descriptor instead.
func (*OfferDecision) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{23}
}

func (x *OfferDecision) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

func (x *OfferDecision) GetEphemeralPubkey() []byte {
	if x != nil {
		return x.EphemeralPubkey
	}
	return nil
}

func (x *OfferDecision) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type SettlementPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PreimageHash  []byte                 `protobuf:"bytes,1,opt,name=preimage_hash,json=preimageHash,proto3" json:"preimage_hash,omitempty"` // 32
	PreimageBody  []byte                 `protobuf:"bytes,2,opt,name=preimage_body,json=preimageBody,proto3" json:"preimage_body,omitempty"` // serialized EntryBody
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementPush) Reset() {
	*x = SettlementPush{}
	mi := &file_proto_rpc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementPush) ProtoMessage() {}

func (x *SettlementPush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementPush.ProtoReflect.Descriptor instead.
func (*SettlementPush) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{24}
}

func (x *SettlementPush) GetPreimageHash() []byte {
	if x != nil {
		return x.PreimageHash
	}
	return nil
}

func (x *SettlementPush) GetPreimageBody() []byte {
	if x != nil {
		return x.PreimageBody
	}
	return nil
}

var File_proto_rpc_proto protoreflect.FileDescriptor

const file_proto_rpc_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/rpc.proto\x12\x11tokenbay.proto.v1\x1a\x13proto/balance.proto\x1a\x14proto/envelope.proto\"8\n" +
	"\bRpcError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\\\n" +
	"\n" +
	"RpcRequest\x124\n" +
	"\x06method\x18\x01 \x01(\x0e2\x1c.tokenbay.proto.v1.RpcMethodR\x06method\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x90\x01\n" +
	"\vRpcResponse\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.tokenbay.proto.v1.RpcStatusR\x06status\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x121\n" +
	"\x05error\x18\x03 \x01(\v2\x1b.tokenbay.proto.v1.RpcErrorR\x05error\"\xb6\x01\n" +
	"\rEnrollRequest\x12'\n" +
	"\x0fidentity_pubkey\x18\x01 \x01(\fR\x0eidentityPubkey\x12\x12\n" +
	"\x04role\x18\x02 \x01(\rR\x04role\x12/\n" +
	"\x13account_fingerprint\x18\x03 \x01(\fR\x12accountFingerprint\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\x12!\n" +
	"\fconsumer_sig\x18\x05 \x01(\fR\vconsumerSig\"\x95\x01\n" +
	"\x0eEnrollResponse\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\fR\n" +
	"identityId\x122\n" +
	"\x15starter_grant_credits\x18\x02 \x01(\x04R\x13starterGrantCredits\x12.\n" +
	"\x13starter_grant_entry\x18\x03 \x01(\fR\x11starterGrantEntry\"\x83\x01\n" +
	"\x0eBrokerResponse\x12\x1f\n" +
	"\vseeder_addr\x18\x01 \x01(\fR\n" +
	"seederAddr\x12#\n" +
	"\rseeder_pubkey\x18\x02 \x01(\fR\fseederPubkey\x12+\n" +
	"\x11reservation_token\x18\x03 \x01(\fR\x10reservationToken\"$\n" +
	"\n" +
	"NoCapacity\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"1\n" +
	"\x0eBalanceRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\fR\n" +
	"identityId\"W\n" +
	"\rSettleRequest\x12#\n" +
	"\rpreimage_hash\x18\x01 \x01(\fR\fpreimageHash\x12!\n" +
	"\fconsumer_sig\x18\x02 \x01(\fR\vconsumerSig\"\v\n" +
	"\tSettleAck\"\xa9\x01\n" +
	"\vUsageReport\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\fR\trequestId\x12!\n" +
	"\finput_tokens\x18\x02 \x01(\rR\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x03 \x01(\rR\foutputTokens\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"seeder_sig\x18\x05 \x01(\fR\tseederSig\"\n" +
	"\n" +
	"\bUsageAck\"\x98\x01\n" +
	"\rAdvertisement\x12\x16\n" +
	"\x06models\x18\x01 \x03(\tR\x06models\x12\x1f\n" +
	"\vmax_context\x18\x02 \x01(\rR\n" +
	"maxContext\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable\x12\x1a\n" +
	"\bheadroom\x18\x04 \x01(\x02R\bheadroom\x12\x14\n" +
	"\x05tiers\x18\x05 \x01(\rR\x05tiers\"\x0e\n" +
	"\fAdvertiseAck\"\x81\x01\n" +
	"\x0fTransferRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\fR\n" +
	"identityId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x1f\n" +
	"\vdest_region\x18\x03 \x01(\tR\n" +
	"destRegion\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\"\x82\x01\n" +
	"\rTransferProof\x121\n" +
	"\x15source_chain_tip_hash\x18\x01 \x01(\fR\x12sourceChainTipHash\x12\x1d\n" +
	"\n" +
	"source_seq\x18\x02 \x01(\x04R\tsourceSeq\x12\x1f\n" +
	"\vtracker_sig\x18\x03 \x01(\fR\n" +
	"trackerSig\"\x15\n" +
	"\x13StunAllocateRequest\";\n" +
	"\x14StunAllocateResponse\x12#\n" +
	"\rexternal_addr\x18\x01 \x01(\tR\fexternalAddr\"5\n" +
	"\x14TurnRelayOpenRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\fR\tsessionId\"T\n" +
	"\x15TurnRelayOpenResponse\x12%\n" +
	"\x0erelay_endpoint\x18\x01 \x01(\tR\rrelayEndpoint\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05token\"/\n" +
	"\rHeartbeatPing\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\f\n" +
	"\x01t\x18\x02 \x01(\x04R\x01t\"!\n" +
	"\rHeartbeatPong\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\"\xbd\x01\n" +
	"\tOfferPush\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\fR\n" +
	"consumerId\x12#\n" +
	"\renvelope_hash\x18\x02 \x01(\fR\fenvelopeHash\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12(\n" +
	"\x10max_input_tokens\x18\x04 \x01(\rR\x0emaxInputTokens\x12*\n" +
	"\x11max_output_tokens\x18\x05 \x01(\rR\x0fmaxOutputTokens\"w\n" +
	"\rOfferDecision\x12\x16\n" +
	"\x06accept\x18\x01 \x01(\bR\x06accept\x12)\n" +
	"\x10ephemeral_pubkey\x18\x02 \x01(\fR\x0fephemeralPubkey\x12#\n" +
	"\rreject_reason\x18\x03 \x01(\tR\frejectReason\"Z\n" +
	"\x0eSettlementPush\x12#\n" +
	"\rpreimage_hash\x18\x01 \x01(\fR\fpreimageHash\x12#\n" +
	"\rpreimage_body\x18\x02 \x01(\fR\fpreimageBody*\xa2\x02\n" +
	"\tRpcMethod\x12\x1a\n" +
	"\x16RPC_METHOD_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RPC_METHOD_ENROLL\x10\x01\x12\x1d\n" +
	"\x19RPC_METHOD_BROKER_REQUEST\x10\x02\x12\x16\n" +
	"\x12RPC_METHOD_BALANCE\x10\x03\x12\x15\n" +
	"\x11RPC_METHOD_SETTLE\x10\x04\x12\x1b\n" +
	"\x17RPC_METHOD_USAGE_REPORT\x10\x05\x12\x18\n" +
	"\x14RPC_METHOD_ADVERTISE\x10\x06\x12\x1f\n" +
	"\x1bRPC_METHOD_TRANSFER_REQUEST\x10\a\x12\x1c\n" +
	"\x18RPC_METHOD_STUN_ALLOCATE\x10\b\x12\x1e\n" +
	"\x1aRPC_METHOD_TURN_RELAY_OPEN\x10\t*\xd8\x01\n" +
	"\tRpcStatus\x12\x1a\n" +
	"\x16RPC_STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rRPC_STATUS_OK\x10\x01\x12\x16\n" +
	"\x12RPC_STATUS_INVALID\x10\x02\x12\x1a\n" +
	"\x16RPC_STATUS_NO_CAPACITY\x10\x03\x12\x15\n" +
	"\x11RPC_STATUS_FROZEN\x10\x04\x12\x17\n" +
	"\x13RPC_STATUS_INTERNAL\x10\x05\x12\x1e\n" +
	"\x1aRPC_STATUS_UNAUTHENTICATED\x10\x06\x12\x18\n" +
	"\x14RPC_STATUS_NOT_FOUND\x10\aB-Z+github.com/token-bay/token-bay/shared/protob\x06proto3"

var (
	file_proto_rpc_proto_rawDescOnce sync.Once
	file_proto_rpc_proto_rawDescData []byte
)

func file_proto_rpc_proto_rawDescGZIP() []byte {
	file_proto_rpc_proto_rawDescOnce.Do(func() {
		file_proto_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rpc_proto_rawDesc), len(file_proto_rpc_proto_rawDesc)))
	})
	return file_proto_rpc_proto_rawDescData
}

var file_proto_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_rpc_proto_goTypes = []any{
	(RpcMethod)(0),                // 0: tokenbay.proto.v1.RpcMethod
	(RpcStatus)(0),                // 1: tokenbay.proto.v1.RpcStatus
	(*RpcError)(nil),              // 2: tokenbay.proto.v1.RpcError
	(*RpcRequest)(nil),            // 3: tokenbay.proto.v1.RpcRequest
	(*RpcResponse)(nil),           // 4: tokenbay.proto.v1.RpcResponse
	(*EnrollRequest)(nil),         // 5: tokenbay.proto.v1.EnrollRequest
	(*EnrollResponse)(nil),        // 6: tokenbay.proto.v1.EnrollResponse
	(*BrokerResponse)(nil),        // 7: tokenbay.proto.v1.BrokerResponse
	(*NoCapacity)(nil),            // 8: tokenbay.proto.v1.NoCapacity
	(*BalanceRequest)(nil),        // 9: tokenbay.proto.v1.BalanceRequest
	(*SettleRequest)(nil),         // 10: tokenbay.proto.v1.SettleRequest
	(*SettleAck)(nil),             // 11: tokenbay.proto.v1.SettleAck
	(*UsageReport)(nil),           // 12: tokenbay.proto.v1.UsageReport
	(*UsageAck)(nil),              // 13: tokenbay.proto.v1.UsageAck
	(*Advertisement)(nil),         // 14: tokenbay.proto.v1.Advertisement
	(*AdvertiseAck)(nil),          // 15: tokenbay.proto.v1.AdvertiseAck
	(*TransferRequest)(nil),       // 16: tokenbay.proto.v1.TransferRequest
	(*TransferProof)(nil),         // 17: tokenbay.proto.v1.TransferProof
	(*StunAllocateRequest)(nil),   // 18: tokenbay.proto.v1.StunAllocateRequest
	(*StunAllocateResponse)(nil),  // 19: tokenbay.proto.v1.StunAllocateResponse
	(*TurnRelayOpenRequest)(nil),  // 20: tokenbay.proto.v1.TurnRelayOpenRequest
	(*TurnRelayOpenResponse)(nil), // 21: tokenbay.proto.v1.TurnRelayOpenResponse
	(*HeartbeatPing)(nil),         // 22: tokenbay.proto.v1.HeartbeatPing
	(*HeartbeatPong)(nil),         // 23: tokenbay.proto.v1.HeartbeatPong
	(*OfferPush)(nil),             // 24: tokenbay.proto.v1.OfferPush
	(*OfferDecision)(nil),         // 25: tokenbay.proto.v1.OfferDecision
	(*SettlementPush)(nil),        // 26: tokenbay.proto.v1.SettlementPush
}
var file_proto_rpc_proto_depIdxs = []int32{
	0, // 0: tokenbay.proto.v1.RpcRequest.method:type_name -> tokenbay.proto.v1.RpcMethod
	1, // 1: tokenbay.proto.v1.RpcResponse.status:type_name -> tokenbay.proto.v1.RpcStatus
	2, // 2: tokenbay.proto.v1.RpcResponse.error:type_name -> tokenbay.proto.v1.RpcError
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_rpc_proto_init() }
func file_proto_rpc_proto_init() {
	if File_proto_rpc_proto != nil {
		return
	}
	file_proto_balance_proto_init()
	file_proto_envelope_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rpc_proto_rawDesc), len(file_proto_rpc_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_rpc_proto_goTypes,
		DependencyIndexes: file_proto_rpc_proto_depIdxs,
		EnumInfos:         file_proto_rpc_proto_enumTypes,
		MessageInfos:      file_proto_rpc_proto_msgTypes,
	}.Build()
	File_proto_rpc_proto = out.File
	file_proto_rpc_proto_goTypes = nil
	file_proto_rpc_proto_depIdxs = nil
}
