// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: admission/admission.proto

package admission

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TickSource classifies how a seeder produced its headroom_estimate.
// TICK_SOURCE_UNSPECIFIED is rejected by ValidateFetchHeadroomResponse.
// Imported by tracker heartbeat once that proto exists (admission-design
// §11.1).
type TickSource int32

const (
	TickSource_TICK_SOURCE_UNSPECIFIED TickSource = 0
	TickSource_TICK_SOURCE_HEURISTIC   TickSource = 1
	TickSource_TICK_SOURCE_USAGE_PROBE TickSource = 2
)

// Enum value maps for TickSource.
var (
	TickSource_name = map[int32]string{
		0: "TICK_SOURCE_UNSPECIFIED",
		1: "TICK_SOURCE_HEURISTIC",
		2: "TICK_SOURCE_USAGE_PROBE",
	}
	TickSource_value = map[string]int32{
		"TICK_SOURCE_UNSPECIFIED": 0,
		"TICK_SOURCE_HEURISTIC":   1,
		"TICK_SOURCE_USAGE_PROBE": 2,
	}
)

func (x TickSource) Enum() *TickSource {
	p := new(TickSource)
	*p = x
	return p
}

func (x TickSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TickSource) Descriptor() protoreflect.EnumDescriptor {
	return file_admission_admission_proto_enumTypes[0].Descriptor()
}

func (TickSource) Type() protoreflect.EnumType {
	return &file_admission_admission_proto_enumTypes[0]
}

func (x TickSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TickSource.Descriptor instead.
func (TickSource) EnumDescriptor() ([]byte, []int) {
	return file_admission_admission_proto_rawDescGZIP(), []int{0}
}

// CreditAttestationBody — tracker-signed portable credit-history
// attestation. Spec:
// docs/superpowers/specs/admission/2026-04-25-admission-design.md §4.1.
// Two-message split for canonical signing: tracker signs
// DeterministicMarshal(body).
type CreditAttestationBody struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	IdentityId            []byte                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`                                   // 32 bytes — consumer Ed25519 pubkey hash
	IssuerTrackerId       []byte                 `protobuf:"bytes,2,opt,name=issuer_tracker_id,json=issuerTrackerId,proto3" json:"issuer_tracker_id,omitempty"`                  // 32 bytes — issuing tracker pubkey hash
	Score                 uint32                 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`                                                              // fixed-point 0..10000 (= 0.0..1.0)
	TenureDays            uint32                 `protobuf:"varint,4,opt,name=tenure_days,json=tenureDays,proto3" json:"tenure_days,omitempty"`                                  // capped 365
	SettlementReliability uint32                 `protobuf:"varint,5,opt,name=settlement_reliability,json=settlementReliability,proto3" json:"settlement_reliability,omitempty"` // fixed-point 0..10000
	DisputeRate           uint32                 `protobuf:"varint,6,opt,name=dispute_rate,json=disputeRate,proto3" json:"dispute_rate,omitempty"`                               // fixed-point 0..10000 (low = good)
	NetCreditFlow_30D     int64                  `protobuf:"varint,7,opt,name=net_credit_flow_30d,json=netCreditFlow30d,proto3" json:"net_credit_flow_30d,omitempty"`            // signed credit delta over rolling 30d
	BalanceCushionLog2    int32                  `protobuf:"varint,8,opt,name=balance_cushion_log2,json=balanceCushionLog2,proto3" json:"balance_cushion_log2,omitempty"`        // log2(balance/starter_grant), clamped [-8, 8]
	ComputedAt            uint64                 `protobuf:"varint,9,opt,name=computed_at,json=computedAt,proto3" json:"computed_at,omitempty"`                                  // unix seconds; tracker wall-clock
	ExpiresAt             uint64                 `protobuf:"varint,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`                                    // computed_at + ttl
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreditAttestationBody) Reset() {
	*x = CreditAttestationBody{}
	mi := &file_admission_admission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditAttestationBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditAttestationBody) ProtoMessage() {}

func (x *CreditAttestationBody) ProtoReflect() protoreflect.Message {
	mi := &file_admission_admission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditAttestationBody.ProtoReflect.Descriptor instead.
func (*CreditAttestationBody) Descriptor() ([]byte, []int) {
	return file_admission_admission_proto_rawDescGZIP(), []int{0}
}

func (x *CreditAttestationBody) GetIdentityId() []byte {
	if x != nil {
		return x.IdentityId
	}
	return nil
}

func (x *CreditAttestationBody) GetIssuerTrackerId() []byte {
	if x != nil {
		return x.IssuerTrackerId
	}
	return nil
}

func (x *CreditAttestationBody) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CreditAttestationBody) GetTenureDays() uint32 {
	if x != nil {
		return x.TenureDays
	}
	return 0
}

func (x *CreditAttestationBody) GetSettlementReliability() uint32 {
	if x != nil {
		return x.SettlementReliability
	}
	return 0
}

func (x *CreditAttestationBody) GetDisputeRate() uint32 {
	if x != nil {
		return x.DisputeRate
	}
	return 0
}

func (x *CreditAttestationBody) GetNetCreditFlow_30D() int64 {
	if x != nil {
		return x.NetCreditFlow_30D
	}
	return 0
}

func (x *CreditAttestationBody) GetBalanceCushionLog2() int32 {
	if x != nil {
		return x.BalanceCushionLog2
	}
	return 0
}

func (x *CreditAttestationBody) GetComputedAt() uint64 {
	if x != nil {
		return x.ComputedAt
	}
	return 0
}

func (x *CreditAttestationBody) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// SignedCreditAttestation — wire form. Verifier recovers signed bytes via
// shared/signing.DeterministicMarshal(body).
type SignedCreditAttestation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *CreditAttestationBody `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	TrackerSig    []byte                 `protobuf:"bytes,2,opt,name=tracker_sig,json=trackerSig,proto3" json:"tracker_sig,omitempty"` // 64 bytes — Ed25519 signature
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedCreditAttestation) Reset() {
	*x = SignedCreditAttestation{}
	mi := &file_admission_admission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedCreditAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedCreditAttestation) ProtoMessage() {}

func (x *SignedCreditAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_admission_admission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedCreditAttestation.ProtoReflect.Descriptor instead.
func (*SignedCreditAttestation) Descriptor() ([]byte, []int) {
	return file_admission_admission_proto_rawDescGZIP(), []int{1}
}

func (x *SignedCreditAttestation) GetBody() *CreditAttestationBody {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SignedCreditAttestation) GetTrackerSig() []byte {
	if x != nil {
		return x.TrackerSig
	}
	return nil
}

// FetchHeadroomRequest — tracker-initiated, unsigned (rides the
// already-authenticated tracker↔seeder connection). Spec §3.2.
type FetchHeadroomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestNonce  uint64                 `protobuf:"varint,1,opt,name=request_nonce,json=requestNonce,proto3" json:"request_nonce,omitempty"`
	ModelFilter   string                 `protobuf:"bytes,2,opt,name=model_filter,json=modelFilter,proto3" json:"model_filter,omitempty"` // optional; "" for any model
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchHeadroomRequest) Reset() {
	*x = FetchHeadroomRequest{}
	mi := &file_admission_admission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchHeadroomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchHeadroomRequest) ProtoMessage() {}

func (x *FetchHeadroomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admission_admission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchHeadroomRequest.ProtoReflect.Descriptor instead.
func (*FetchHeadroomRequest) Descriptor() ([]byte, []int) {
	return file_admission_admission_proto_rawDescGZIP(), []int{2}
}

func (x *FetchHeadroomRequest) GetRequestNonce() uint64 {
	if x != nil {
		return x.RequestNonce
	}
	return 0
}

func (x *FetchHeadroomRequest) GetModelFilter() string {
	if x != nil {
		return x.ModelFilter
	}
	return ""
}

type FetchHeadroomResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestNonce     uint64                 `protobuf:"varint,1,opt,name=request_nonce,json=requestNonce,proto3" json:"request_nonce,omitempty"`
	HeadroomEstimate uint32                 `protobuf:"varint,2,opt,name=headroom_estimate,json=headroomEstimate,proto3" json:"headroom_estimate,omitempty"` // fixed-point 0..10000
	Source           TickSource             `protobuf:"varint,3,opt,name=source,proto3,enum=tokenbay.admission.v1.TickSource" json:"source,omitempty"`
	ProbeAgeS        uint32                 `protobuf:"varint,4,opt,name=probe_age_s,json=probeAgeS,proto3" json:"probe_age_s,omitempty"`
	CanProbeUsage    bool                   `protobuf:"varint,5,opt,name=can_probe_usage,json=canProbeUsage,proto3" json:"can_probe_usage,omitempty"`
	PerModel         []*PerModelHeadroom    `protobuf:"bytes,6,rep,name=per_model,json=perModel,proto3" json:"per_model,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FetchHeadroomResponse) Reset() {
	*x = FetchHeadroomResponse{}
	mi := &file_admission_admission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchHeadroomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchHeadroomResponse) ProtoMessage() {}

func (x *FetchHeadroomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admission_admission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchHeadroomResponse.ProtoReflect.Descriptor instead.
func (*FetchHeadroomResponse) Descriptor() ([]byte, []int) {
	return file_admission_admission_proto_rawDescGZIP(), []int{3}
}

func (x *FetchHeadroomResponse) GetRequestNonce() uint64 {
	if x != nil {
		return x.RequestNonce
	}
	return 0
}

func (x *FetchHeadroomResponse) GetHeadroomEstimate() uint32 {
	if x != nil {
		return x.HeadroomEstimate
	}
	return 0
}

func (x *FetchHeadroomResponse) GetSource() TickSource {
	if x != nil {
		return x.Source
	}
	return TickSource_TICK_SOURCE_UNSPECIFIED
}

func (x *FetchHeadroomResponse) GetProbeAgeS() uint32 {
	if x != nil {
		return x.ProbeAgeS
	}
	return 0
}

func (x *FetchHeadroomResponse) GetCanProbeUsage() bool {
	if x != nil {
		return x.CanProbeUsage
	}
	return false
}

func (x *FetchHeadroomResponse) GetPerModel() []*PerModelHeadroom {
	if x != nil {
		return x.PerModel
	}
	return nil
}

type PerModelHeadroom struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Model            string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	HeadroomEstimate uint32                 `protobuf:"varint,2,opt,name=headroom_estimate,json=headroomEstimate,proto3" json:"headroom_estimate,omitempty"` // fixed-point 0..10000
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PerModelHeadroom) Reset() {
	*x = PerModelHeadroom{}
	mi := &file_admission_admission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerModelHeadroom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerModelHeadroom) ProtoMessage() {}

func (x *PerModelHeadroom) ProtoReflect() protoreflect.Message {
	mi := &file_admission_admission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerModelHeadroom.ProtoReflect.Descriptor instead.
func (*PerModelHeadroom) Descriptor() ([]byte, []int) {
	return file_admission_admission_proto_rawDescGZIP(), []int{4}
}

func (x *PerModelHeadroom) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PerModelHeadroom) GetHeadroomEstimate() uint32 {
	if x != nil {
		return x.HeadroomEstimate
	}
	return 0
}

var File_admission_admission_proto protoreflect.FileDescriptor

const file_admission_admission_proto_rawDesc = "" +
	"\n" +
	"\x19admission/admission.proto\x12\x15tokenbay.admission.v1\"\x96\x03\n" +
	"\x15CreditAttestationBody\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\fR\n" +
	"identityId\x12*\n" +
	"\x11issuer_tracker_id\x18\x02 \x01(\fR\x0fissuerTrackerId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\rR\x05score\x12\x1f\n" +
	"\vtenure_days\x18\x04 \x01(\rR\n" +
	"tenureDays\x125\n" +
	"\x16settlement_reliability\x18\x05 \x01(\rR\x15settlementReliability\x12!\n" +
	"\fdispute_rate\x18\x06 \x01(\rR\vdisputeRate\x12-\n" +
	"\x13net_credit_flow_30d\x18\a \x01(\x03R\x10netCreditFlow30d\x120\n" +
	"\x14balance_cushion_log2\x18\b \x01(\x05R\x12balanceCushionLog2\x12\x1f\n" +
	"\vcomputed_at\x18\t \x01(\x04R\n" +
	"computedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\x04R\texpiresAt\"|\n" +
	"\x17SignedCreditAttestation\x12@\n" +
	"\x04body\x18\x01 \x01(\v2,.tokenbay.admission.v1.CreditAttestationBodyR\x04body\x12\x1f\n" +
	"\vtracker_sig\x18\x02 \x01(\fR\n" +
	"trackerSig\"^\n" +
	"\x14FetchHeadroomRequest\x12#\n" +
	"\rrequest_nonce\x18\x01 \x01(\x04R\frequestNonce\x12!\n" +
	"\fmodel_filter\x18\x02 \x01(\tR\vmodelFilter\"\xb2\x02\n" +
	"\x15FetchHeadroomResponse\x12#\n" +
	"\rrequest_nonce\x18\x01 \x01(\x04R\frequestNonce\x12+\n" +
	"\x11headroom_estimate\x18\x02 \x01(\rR\x10headroomEstimate\x129\n" +
	"\x06source\x18\x03 \x01(\x0e2!.tokenbay.admission.v1.TickSourceR\x06source\x12\x1e\n" +
	"\vprobe_age_s\x18\x04 \x01(\rR\tprobeAgeS\x12&\n" +
	"\x0fcan_probe_usage\x18\x05 \x01(\bR\rcanProbeUsage\x12D\n" +
	"\tper_model\x18\x06 \x03(\v2'.tokenbay.admission.v1.PerModelHeadroomR\bperModel\"U\n" +
	"\x10PerModelHeadroom\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12+\n" +
	"\x11headroom_estimate\x18\x02 \x01(\rR\x10headroomEstimate*a\n" +
	"\n" +
	"TickSource\x12\x1b\n" +
	"\x17TICK_SOURCE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TICK_SOURCE_HEURISTIC\x10\x01\x12\x1b\n" +
	"\x17TICK_SOURCE_USAGE_PROBE\x10\x02B1Z/github.com/token-bay/token-bay/shared/admissionb\x06proto3"

var (
	file_admission_admission_proto_rawDescOnce sync.Once
	file_admission_admission_proto_rawDescData []byte
)

func file_admission_admission_proto_rawDescGZIP() []byte {
	file_admission_admission_proto_rawDescOnce.Do(func() {
		file_admission_admission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admission_admission_proto_rawDesc), len(file_admission_admission_proto_rawDesc)))
	})
	return file_admission_admission_proto_rawDescData
}

var file_admission_admission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_admission_admission_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_admission_admission_proto_goTypes = []any{
	(TickSource)(0),                 // 0: tokenbay.admission.v1.TickSource
	(*CreditAttestationBody)(nil),   // 1: tokenbay.admission.v1.CreditAttestationBody
	(*SignedCreditAttestation)(nil), // 2: tokenbay.admission.v1.SignedCreditAttestation
	(*FetchHeadroomRequest)(nil),    // 3: tokenbay.admission.v1.FetchHeadroomRequest
	(*FetchHeadroomResponse)(nil),   // 4: tokenbay.admission.v1.FetchHeadroomResponse
	(*PerModelHeadroom)(nil),        // 5: tokenbay.admission.v1.PerModelHeadroom
}
var file_admission_admission_proto_depIdxs = []int32{
	1, // 0: tokenbay.admission.v1.SignedCreditAttestation.body:type_name -> tokenbay.admission.v1.CreditAttestationBody
	0, // 1: tokenbay.admission.v1.FetchHeadroomResponse.source:type_name -> tokenbay.admission.v1.TickSource
	5, // 2: tokenbay.admission.v1.FetchHeadroomResponse.per_model:type_name -> tokenbay.admission.v1.PerModelHeadroom
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_admission_admission_proto_init() }
func file_admission_admission_proto_init() {
	if File_admission_admission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admission_admission_proto_rawDesc), len(file_admission_admission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admission_admission_proto_goTypes,
		DependencyIndexes: file_admission_admission_proto_depIdxs,
		EnumInfos:         file_admission_admission_proto_enumTypes,
		MessageInfos:      file_admission_admission_proto_msgTypes,
	}.Build()
	File_admission_admission_proto = out.File
	file_admission_admission_proto_goTypes = nil
	file_admission_admission_proto_depIdxs = nil
}
