// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: federation/federation.proto

package federation

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kind classifies an Envelope's inner payload. Forward-compat: unknown
// kinds at the receiver MUST be parsed and dropped, not crashed on.
type Kind int32

const (
	Kind_KIND_UNSPECIFIED           Kind = 0
	Kind_KIND_HELLO                 Kind = 1
	Kind_KIND_PEER_AUTH             Kind = 2
	Kind_KIND_PEERING_ACCEPT        Kind = 3
	Kind_KIND_PEERING_REJECT        Kind = 4
	Kind_KIND_ROOT_ATTESTATION      Kind = 5
	Kind_KIND_EQUIVOCATION_EVIDENCE Kind = 6
	Kind_KIND_PING                  Kind = 7
	Kind_KIND_PONG                  Kind = 8
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_HELLO",
		2: "KIND_PEER_AUTH",
		3: "KIND_PEERING_ACCEPT",
		4: "KIND_PEERING_REJECT",
		5: "KIND_ROOT_ATTESTATION",
		6: "KIND_EQUIVOCATION_EVIDENCE",
		7: "KIND_PING",
		8: "KIND_PONG",
	}
	Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":           0,
		"KIND_HELLO":                 1,
		"KIND_PEER_AUTH":             2,
		"KIND_PEERING_ACCEPT":        3,
		"KIND_PEERING_REJECT":        4,
		"KIND_ROOT_ATTESTATION":      5,
		"KIND_EQUIVOCATION_EVIDENCE": 6,
		"KIND_PING":                  7,
		"KIND_PONG":                  8,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_federation_federation_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_federation_federation_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_federation_federation_proto_rawDescGZIP(), []int{0}
}

// Envelope wraps every steady-state and handshake message exchanged
// between trackers. The receiver verifies sender_sig over payload
// against the peer's Ed25519 public key.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      []byte                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"` // 32 bytes — sender tracker_id (= sha256(pubkey))
	Kind          Kind                   `protobuf:"varint,2,opt,name=kind,proto3,enum=tokenbay.federation.v1.Kind" json:"kind,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                      // serialized inner message
	SenderSig     []byte                 `protobuf:"bytes,4,opt,name=sender_sig,json=senderSig,proto3" json:"sender_sig,omitempty"` // 64 bytes — Ed25519(payload) by sender
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_federation_federation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_federation_federation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_federation_federation_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSenderId() []byte {
	if x != nil {
		return x.SenderId
	}
	return nil
}

func (x *Envelope) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNSPECIFIED
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSenderSig() []byte {
	if x != nil {
		return x.SenderSig
	}
	return nil
}

type Hello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TrackerId       []byte                 `protobuf:"bytes,1,opt,name=tracker_id,json=trackerId,proto3" json:"tracker_id,omitempty"` // 32 bytes
	ProtocolVersion uint32                 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Nonce           []byte                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"` // 32 bytes
	Features        []string               `protobuf:"bytes,4,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_federation_federation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_federation_federation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_federation_federation_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetTrackerId() []byte {
	if x != nil {
		return x.TrackerId
	}
	return nil
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Hello) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

type PeerAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NonceSig      []byte                 `protobuf:"bytes,1,opt,name=nonce_sig,json=nonceSig,proto3" json:"nonce_sig,omitempty"` // 64 bytes — Ed25519(counterparty Hello.nonce)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerAuth) Reset() {
	*x = PeerAuth{}
	mi := &file_federation_federation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerAuth) ProtoMessage() {}

func (x *PeerAuth) ProtoReflect() protoreflect.Message {
	mi := &file_federation_federation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerAuth.ProtoReflect.Descriptor instead.
func (*PeerAuth) Descriptor() ([]byte, []int) {
	return file_federation_federation_proto_rawDescGZIP(), []int{2}
}

func (x *PeerAuth) GetNonceSig() []byte {
	if x != nil {
		return x.NonceSig
	}
	return nil
}

type PeeringAccept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DedupeTtlS    uint32                 `protobuf:"varint,1,opt,name=dedupe_ttl_s,json=dedupeTtlS,proto3" json:"dedupe_ttl_s,omitempty"`
	GossipRateQps uint32                 `protobuf:"varint,2,opt,name=gossip_rate_qps,json=gossipRateQps,proto3" json:"gossip_rate_qps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeeringAccept) Reset() {
	*x = PeeringAccept{}
	mi := &file_federation_federation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeeringAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeeringAccept) ProtoMessage() {}

func (x *PeeringAccept) ProtoReflect() protoreflect.Message {
	mi := &file_federation_federation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeeringAccept.ProtoReflect.Descriptor instead.
func (*PeeringAccept) Descriptor() ([]byte, []int) {
	return file_federation_federation_proto_rawDescGZIP(), []int{3}
}

func (x *PeeringAccept) GetDedupeTtlS() uint32 {
	if x != nil {
		return x.DedupeTtlS
	}
	return 0
}

func (x *PeeringAccept) GetGossipRateQps() uint32 {
	if x != nil {
		return x.GossipRateQps
	}
	return 0
}

type PeeringReject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeeringReject) Reset() {
	*x = PeeringReject{}
	mi := &file_federation_federation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeeringReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeeringReject) ProtoMessage() {}

func (x *PeeringReject) ProtoReflect() protoreflect.Message {
	mi := &file_federation_federation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeeringReject.ProtoReflect.Descriptor instead.
func (*PeeringReject) Descriptor() ([]byte, []int) {
	return file_federation_federation_proto_rawDescGZIP(), []int{4}
}

func (x *PeeringReject) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RootAttestation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackerId     []byte                 `protobuf:"bytes,1,opt,name=tracker_id,json=trackerId,proto3" json:"tracker_id,omitempty"` // 32 bytes
	Hour          uint64                 `protobuf:"varint,2,opt,name=hour,proto3" json:"hour,omitempty"`
	MerkleRoot    []byte                 `protobuf:"bytes,3,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"` // exactly storage.PutMerkleRoot's root bytes
	TrackerSig    []byte                 `protobuf:"bytes,4,opt,name=tracker_sig,json=trackerSig,proto3" json:"tracker_sig,omitempty"` // 64 bytes — exactly storage.PutMerkleRoot's tracker_sig
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootAttestation) Reset() {
	*x = RootAttestation{}
	mi := &file_federation_federation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootAttestation) ProtoMessage() {}

func (x *RootAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_federation_federation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootAttestation.ProtoReflect.Descriptor instead.
func (*RootAttestation) Descriptor() ([]byte, []int) {
	return file_federation_federation_proto_rawDescGZIP(), []int{5}
}

func (x *RootAttestation) GetTrackerId() []byte {
	if x != nil {
		return x.TrackerId
	}
	return nil
}

func (x *RootAttestation) GetHour() uint64 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *RootAttestation) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *RootAttestation) GetTrackerSig() []byte {
	if x != nil {
		return x.TrackerSig
	}
	return nil
}

type EquivocationEvidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackerId     []byte                 `protobuf:"bytes,1,opt,name=tracker_id,json=trackerId,proto3" json:"tracker_id,omitempty"` // offender
	Hour          uint64                 `protobuf:"varint,2,opt,name=hour,proto3" json:"hour,omitempty"`
	RootA         []byte                 `protobuf:"bytes,3,opt,name=root_a,json=rootA,proto3" json:"root_a,omitempty"`
	SigA          []byte                 `protobuf:"bytes,4,opt,name=sig_a,json=sigA,proto3" json:"sig_a,omitempty"`
	RootB         []byte                 `protobuf:"bytes,5,opt,name=root_b,json=rootB,proto3" json:"root_b,omitempty"`
	SigB          []byte                 `protobuf:"bytes,6,opt,name=sig_b,json=sigB,proto3" json:"sig_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquivocationEvidence) Reset() {
	*x = EquivocationEvidence{}
	mi := &file_federation_federation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquivocationEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquivocationEvidence) ProtoMessage() {}

func (x *EquivocationEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_federation_federation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquivocationEvidence.ProtoReflect.Descriptor instead.
func (*EquivocationEvidence) Descriptor() ([]byte, []int) {
	return file_federation_federation_proto_rawDescGZIP(), []int{6}
}

func (x *EquivocationEvidence) GetTrackerId() []byte {
	if x != nil {
		return x.TrackerId
	}
	return nil
}

func (x *EquivocationEvidence) GetHour() uint64 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *EquivocationEvidence) GetRootA() []byte {
	if x != nil {
		return x.RootA
	}
	return nil
}

func (x *EquivocationEvidence) GetSigA() []byte {
	if x != nil {
		return x.SigA
	}
	return nil
}

func (x *EquivocationEvidence) GetRootB() []byte {
	if x != nil {
		return x.RootB
	}
	return nil
}

func (x *EquivocationEvidence) GetSigB() []byte {
	if x != nil {
		return x.SigB
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_federation_federation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_federation_federation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_federation_federation_proto_rawDescGZIP(), []int{7}
}

func (x *Ping) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_federation_federation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_federation_federation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_federation_federation_proto_rawDescGZIP(), []int{8}
}

func (x *Pong) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

var File_federation_federation_proto protoreflect.FileDescriptor

const file_federation_federation_proto_rawDesc = "" +
	"\n" +
	"\x1bfederation/federation.proto\x12\x16tokenbay.federation.v1\"\x92\x01\n" +
	"\bEnvelope\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\fR\bsenderId\x120\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1c.tokenbay.federation.v1.KindR\x04kind\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"sender_sig\x18\x04 \x01(\fR\tsenderSig\"\x83\x01\n" +
	"\x05Hello\x12\x1d\n" +
	"\n" +
	"tracker_id\x18\x01 \x01(\fR\ttrackerId\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\x12\x1a\n" +
	"\bfeatures\x18\x04 \x03(\tR\bfeatures\"'\n" +
	"\bPeerAuth\x12\x1b\n" +
	"\tnonce_sig\x18\x01 \x01(\fR\bnonceSig\"Y\n" +
	"\rPeeringAccept\x12 \n" +
	"\fdedupe_ttl_s\x18\x01 \x01(\rR\n" +
	"dedupeTtlS\x12&\n" +
	"\x0fgossip_rate_qps\x18\x02 \x01(\rR\rgossipRateQps\"'\n" +
	"\rPeeringReject\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x86\x01\n" +
	"\x0fRootAttestation\x12\x1d\n" +
	"\n" +
	"tracker_id\x18\x01 \x01(\fR\ttrackerId\x12\x12\n" +
	"\x04hour\x18\x02 \x01(\x04R\x04hour\x12\x1f\n" +
	"\vmerkle_root\x18\x03 \x01(\fR\n" +
	"merkleRoot\x12\x1f\n" +
	"\vtracker_sig\x18\x04 \x01(\fR\n" +
	"trackerSig\"\xa1\x01\n" +
	"\x14EquivocationEvidence\x12\x1d\n" +
	"\n" +
	"tracker_id\x18\x01 \x01(\fR\ttrackerId\x12\x12\n" +
	"\x04hour\x18\x02 \x01(\x04R\x04hour\x12\x15\n" +
	"\x06root_a\x18\x03 \x01(\fR\x05rootA\x12\x13\n" +
	"\x05sig_a\x18\x04 \x01(\fR\x04sigA\x12\x15\n" +
	"\x06root_b\x18\x05 \x01(\fR\x05rootB\x12\x13\n" +
	"\x05sig_b\x18\x06 \x01(\fR\x04sigB\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"\x1c\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce*\xcb\x01\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"KIND_HELLO\x10\x01\x12\x12\n" +
	"\x0eKIND_PEER_AUTH\x10\x02\x12\x17\n" +
	"\x13KIND_PEERING_ACCEPT\x10\x03\x12\x17\n" +
	"\x13KIND_PEERING_REJECT\x10\x04\x12\x19\n" +
	"\x15KIND_ROOT_ATTESTATION\x10\x05\x12\x1e\n" +
	"\x1aKIND_EQUIVOCATION_EVIDENCE\x10\x06\x12\r\n" +
	"\tKIND_PING\x10\a\x12\r\n" +
	"\tKIND_PONG\x10\bB2Z0github.com/token-bay/token-bay/shared/federationb\x06proto3"

var (
	file_federation_federation_proto_rawDescOnce sync.Once
	file_federation_federation_proto_rawDescData []byte
)

func file_federation_federation_proto_rawDescGZIP() []byte {
	file_federation_federation_proto_rawDescOnce.Do(func() {
		file_federation_federation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_federation_federation_proto_rawDesc), len(file_federation_federation_proto_rawDesc)))
	})
	return file_federation_federation_proto_rawDescData
}

var (
	file_federation_federation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
	file_federation_federation_proto_msgTypes  = make([]protoimpl.MessageInfo, 9)
	file_federation_federation_proto_goTypes   = []any{
		(Kind)(0),                    // 0: tokenbay.federation.v1.Kind
		(*Envelope)(nil),             // 1: tokenbay.federation.v1.Envelope
		(*Hello)(nil),                // 2: tokenbay.federation.v1.Hello
		(*PeerAuth)(nil),             // 3: tokenbay.federation.v1.PeerAuth
		(*PeeringAccept)(nil),        // 4: tokenbay.federation.v1.PeeringAccept
		(*PeeringReject)(nil),        // 5: tokenbay.federation.v1.PeeringReject
		(*RootAttestation)(nil),      // 6: tokenbay.federation.v1.RootAttestation
		(*EquivocationEvidence)(nil), // 7: tokenbay.federation.v1.EquivocationEvidence
		(*Ping)(nil),                 // 8: tokenbay.federation.v1.Ping
		(*Pong)(nil),                 // 9: tokenbay.federation.v1.Pong
	}
)
var file_federation_federation_proto_depIdxs = []int32{
	0, // 0: tokenbay.federation.v1.Envelope.kind:type_name -> tokenbay.federation.v1.Kind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_federation_federation_proto_init() }
func file_federation_federation_proto_init() {
	if File_federation_federation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_federation_federation_proto_rawDesc), len(file_federation_federation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_federation_federation_proto_goTypes,
		DependencyIndexes: file_federation_federation_proto_depIdxs,
		EnumInfos:         file_federation_federation_proto_enumTypes,
		MessageInfos:      file_federation_federation_proto_msgTypes,
	}.Build()
	File_federation_federation_proto = out.File
	file_federation_federation_proto_goTypes = nil
	file_federation_federation_proto_depIdxs = nil
}
