// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: exhaustionproof/proof.proto

package exhaustionproof

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExhaustionProofV1 is the v1 two-signal rate-limit-exhaustion proof
// attached to every broker_request envelope. Spec:
// docs/superpowers/specs/shared/2026-04-24-wire-format-v1-design.md §5.1.
type ExhaustionProofV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StopFailure   *StopFailure           `protobuf:"bytes,1,opt,name=stop_failure,json=stopFailure,proto3" json:"stop_failure,omitempty"`
	UsageProbe    *UsageProbe            `protobuf:"bytes,2,opt,name=usage_probe,json=usageProbe,proto3" json:"usage_probe,omitempty"`
	CapturedAt    uint64                 `protobuf:"varint,3,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"` // unix seconds — when the proof was assembled
	Nonce         []byte                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`                              // 16 random bytes — proof-level replay protection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExhaustionProofV1) Reset() {
	*x = ExhaustionProofV1{}
	mi := &file_exhaustionproof_proof_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExhaustionProofV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExhaustionProofV1) ProtoMessage() {}

func (x *ExhaustionProofV1) ProtoReflect() protoreflect.Message {
	mi := &file_exhaustionproof_proof_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExhaustionProofV1.ProtoReflect.Descriptor instead.
func (*ExhaustionProofV1) Descriptor() ([]byte, []int) {
	return file_exhaustionproof_proof_proto_rawDescGZIP(), []int{0}
}

func (x *ExhaustionProofV1) GetStopFailure() *StopFailure {
	if x != nil {
		return x.StopFailure
	}
	return nil
}

func (x *ExhaustionProofV1) GetUsageProbe() *UsageProbe {
	if x != nil {
		return x.UsageProbe
	}
	return nil
}

func (x *ExhaustionProofV1) GetCapturedAt() uint64 {
	if x != nil {
		return x.CapturedAt
	}
	return 0
}

func (x *ExhaustionProofV1) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

// StopFailure is the captured StopFailureHookInput payload.
type StopFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matcher       string                 `protobuf:"bytes,1,opt,name=matcher,proto3" json:"matcher,omitempty"`                         // v1: MUST be "rate_limit"
	At            uint64                 `protobuf:"varint,2,opt,name=at,proto3" json:"at,omitempty"`                                  // unix seconds
	ErrorShape    []byte                 `protobuf:"bytes,3,opt,name=error_shape,json=errorShape,proto3" json:"error_shape,omitempty"` // raw JSON Claude Code surfaced — verbatim, no transformation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopFailure) Reset() {
	*x = StopFailure{}
	mi := &file_exhaustionproof_proof_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopFailure) ProtoMessage() {}

func (x *StopFailure) ProtoReflect() protoreflect.Message {
	mi := &file_exhaustionproof_proof_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopFailure.ProtoReflect.Descriptor instead.
func (*StopFailure) Descriptor() ([]byte, []int) {
	return file_exhaustionproof_proof_proto_rawDescGZIP(), []int{1}
}

func (x *StopFailure) GetMatcher() string {
	if x != nil {
		return x.Matcher
	}
	return ""
}

func (x *StopFailure) GetAt() uint64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *StopFailure) GetErrorShape() []byte {
	if x != nil {
		return x.ErrorShape
	}
	return nil
}

// UsageProbe is the parsed output of `claude /usage` run under PTY.
type UsageProbe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            uint64                 `protobuf:"varint,1,opt,name=at,proto3" json:"at,omitempty"`        // unix seconds (when /usage was executed)
	Output        []byte                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"` // raw bytes of /usage TUI output (PTY-captured)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageProbe) Reset() {
	*x = UsageProbe{}
	mi := &file_exhaustionproof_proof_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageProbe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageProbe) ProtoMessage() {}

func (x *UsageProbe) ProtoReflect() protoreflect.Message {
	mi := &file_exhaustionproof_proof_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageProbe.ProtoReflect.Descriptor instead.
func (*UsageProbe) Descriptor() ([]byte, []int) {
	return file_exhaustionproof_proof_proto_rawDescGZIP(), []int{2}
}

func (x *UsageProbe) GetAt() uint64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *UsageProbe) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_exhaustionproof_proof_proto protoreflect.FileDescriptor

const file_exhaustionproof_proof_proto_rawDesc = "" +
	"\n" +
	"\x1bexhaustionproof/proof.proto\x12\x1btokenbay.exhaustionproof.v1\"\xe1\x01\n" +
	"\x11ExhaustionProofV1\x12K\n" +
	"\fstop_failure\x18\x01 \x01(\v2(.tokenbay.exhaustionproof.v1.StopFailureR\vstopFailure\x12H\n" +
	"\vusage_probe\x18\x02 \x01(\v2'.tokenbay.exhaustionproof.v1.UsageProbeR\n" +
	"usageProbe\x12\x1f\n" +
	"\vcaptured_at\x18\x03 \x01(\x04R\n" +
	"capturedAt\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\fR\x05nonce\"X\n" +
	"\vStopFailure\x12\x18\n" +
	"\amatcher\x18\x01 \x01(\tR\amatcher\x12\x0e\n" +
	"\x02at\x18\x02 \x01(\x04R\x02at\x12\x1f\n" +
	"\verror_shape\x18\x03 \x01(\fR\n" +
	"errorShape\"4\n" +
	"\n" +
	"UsageProbe\x12\x0e\n" +
	"\x02at\x18\x01 \x01(\x04R\x02at\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06outputB7Z5github.com/token-bay/token-bay/shared/exhaustionproofb\x06proto3"

var (
	file_exhaustionproof_proof_proto_rawDescOnce sync.Once
	file_exhaustionproof_proof_proto_rawDescData []byte
)

func file_exhaustionproof_proof_proto_rawDescGZIP() []byte {
	file_exhaustionproof_proof_proto_rawDescOnce.Do(func() {
		file_exhaustionproof_proof_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exhaustionproof_proof_proto_rawDesc), len(file_exhaustionproof_proof_proto_rawDesc)))
	})
	return file_exhaustionproof_proof_proto_rawDescData
}

var file_exhaustionproof_proof_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_exhaustionproof_proof_proto_goTypes = []any{
	(*ExhaustionProofV1)(nil), // 0: tokenbay.exhaustionproof.v1.ExhaustionProofV1
	(*StopFailure)(nil),       // 1: tokenbay.exhaustionproof.v1.StopFailure
	(*UsageProbe)(nil),        // 2: tokenbay.exhaustionproof.v1.UsageProbe
}
var file_exhaustionproof_proof_proto_depIdxs = []int32{
	1, // 0: tokenbay.exhaustionproof.v1.ExhaustionProofV1.stop_failure:type_name -> tokenbay.exhaustionproof.v1.StopFailure
	2, // 1: tokenbay.exhaustionproof.v1.ExhaustionProofV1.usage_probe:type_name -> tokenbay.exhaustionproof.v1.UsageProbe
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_exhaustionproof_proof_proto_init() }
func file_exhaustionproof_proof_proto_init() {
	if File_exhaustionproof_proof_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exhaustionproof_proof_proto_rawDesc), len(file_exhaustionproof_proof_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_exhaustionproof_proof_proto_goTypes,
		DependencyIndexes: file_exhaustionproof_proof_proto_depIdxs,
		MessageInfos:      file_exhaustionproof_proof_proto_msgTypes,
	}.Build()
	File_exhaustionproof_proof_proto = out.File
	file_exhaustionproof_proof_proto_goTypes = nil
	file_exhaustionproof_proof_proto_depIdxs = nil
}
